// ─────────────────────────────────────────────────────────────────────────────
// ÉTAPE 3 — ajouter "documents" dans la version SourceLang
//
// Même logique que files-ts.ts mais avec la syntaxe de TON langage :
//   "server";          → directive de mode serveur
//   export fn X(): void { ... }  → déclaration de fonction
//   printf("...");     → affichage
//
// Pour documents.src, on garde la syntaxe printf car c'est du server-side.
// L'icône "pdf" (rouge) est identique aux deux versions —
// c'est CodeEditor qui détecte icon === "pdf" pour rendre DocumentsPanel.
// ─────────────────────────────────────────────────────────────────────────────

import { DEMO_PROJECTS, DemoProject } from "@/src/lib/demo-projects";

export type FileKey =
  | "about"
  | "skills"
  | "experience"
  | "projects"
  | "demos"
  | "documents"   // ← NOUVEAU
  | "contact"
  | "config";

export interface FileData {
  name: string;
  lang: string;
  icon: "ts" | "json" | "mdx" | "pdf" | "src";
  lines: string[];
  demos?: DemoProject[];
}

export const FILES: Record<FileKey, FileData> = {

  // ── about.src ─────────────────────────────────────────────────────────────
  about: {
    name: "about.src",
    lang: "SourceLang",
    icon: "src",
    lines: [
      `<span class="str-t">"component"</span><span class="punc-t">;</span>`,
      ``,
      `<span class="kw2">import</span> <span class="punc-t">{</span> <span class="type-t">Developer</span> <span class="punc-t">}</span> <span class="kw2">from</span> <span class="str-t">"sourcelang/types"</span><span class="punc-t">;</span>`,
      ``,
      `<span class="kw">component</span> <span class="fn-t">About</span><span class="punc-t">():</span> <span class="type-t">Developer</span> <span class="punc-t">{</span>`,
      `  <span class="kw2">return</span> <span class="punc-t">(</span>`,
      `    <span class="punc-t">&lt;</span><span class="type-t">section</span><span class="punc-t">&gt;</span>`,
      ``,
      `      <span class="punc-t">&lt;</span><span class="type-t">h1</span><span class="punc-t">&gt;</span>LAOUITI Malika<span class="punc-t">&lt;/</span><span class="type-t">h1</span><span class="punc-t">&gt;</span>`,
      `      <span class="punc-t">&lt;</span><span class="type-t">h2</span><span class="punc-t">&gt;</span>Fullstack Developer <span class="op-t">&amp;</span> Systems Engineer<span class="punc-t">&lt;/</span><span class="type-t">h2</span><span class="punc-t">&gt;</span>`,
      ``,
      `      <span class="punc-t">&lt;</span><span class="type-t">div</span> <span class="prop-t">class</span><span class="op-t">=</span><span class="str-t">"education"</span><span class="punc-t">&gt;</span>`,
      `        <span class="punc-t">&lt;</span><span class="type-t">p</span><span class="punc-t">&gt;</span>🎓 1st Year Software Engineering — ISSAT Sousse <span class="punc-t">(</span><span class="num-t">2025</span>–present<span class="punc-t">)&lt;/</span><span class="type-t">p</span><span class="punc-t">&gt;</span>`,
      `        <span class="punc-t">&lt;</span><span class="type-t">p</span><span class="punc-t">&gt;</span>🏫 BSc Software Engineering — ISIMM Monastir <span class="punc-t">(</span><span class="num-t">2025</span><span class="punc-t">)</span> — <span class="str-t">Excellent</span> FYP<span class="punc-t">&lt;/</span><span class="type-t">p</span><span class="punc-t">&gt;</span>`,
      `        <span class="punc-t">&lt;</span><span class="type-t">p</span><span class="punc-t">&gt;</span>📡 CCNA 1 Certified — Networking fundamentals<span class="punc-t">&lt;/</span><span class="type-t">p</span><span class="punc-t">&gt;</span>`,
      `        <span class="punc-t">&lt;</span><span class="type-t">p</span><span class="punc-t">&gt;</span>🏅 Bac Technologique — Ibn Khaldoun Jemmel <span class="punc-t">(</span><span class="num-t">15.73</span><span class="op-t">/</span><span class="num-t">20</span><span class="punc-t">)&lt;/</span><span class="type-t">p</span><span class="punc-t">&gt;</span>`,
      `      <span class="punc-t">&lt;/</span><span class="type-t">div</span><span class="punc-t">&gt;</span>`,
      ``,
      `      <span class="punc-t">&lt;</span><span class="type-t">div</span> <span class="prop-t">class</span><span class="op-t">=</span><span class="str-t">"status"</span><span class="punc-t">&gt;</span>`,
      `        <span class="punc-t">&lt;</span><span class="type-t">p</span><span class="punc-t">&gt;</span>💼 Seeking an <span class="kw">internship</span> — software / web / systems development<span class="punc-t">&lt;/</span><span class="type-t">p</span><span class="punc-t">&gt;</span>`,
      `        <span class="punc-t">&lt;</span><span class="type-t">p</span><span class="punc-t">&gt;</span>📍 Monastir <span class="num-t">5020</span> 🇹🇳<span class="punc-t">&lt;/</span><span class="type-t">p</span><span class="punc-t">&gt;</span>`,
      `        <span class="punc-t">&lt;</span><span class="type-t">p</span><span class="punc-t">&gt;</span>⚡ Available <span class="bool-t">immediately</span> — curious, versatile, eager to contribute<span class="punc-t">&lt;/</span><span class="type-t">p</span><span class="punc-t">&gt;</span>`,
      `      <span class="punc-t">&lt;/</span><span class="type-t">div</span><span class="punc-t">&gt;</span>`,
      ``,
      `    <span class="punc-t">&lt;/</span><span class="type-t">section</span><span class="punc-t">&gt;</span>`,
      `  <span class="punc-t">);</span>`,
      `<span class="punc-t">}</span>`,
    ],
  },

  // ── skills.src ────────────────────────────────────────────────────────────
  skills: {
    name: "skills.src",
    lang: "SourceLang",
    icon: "src",
    lines: [
      `<span class="str-t">"server"</span><span class="punc-t">;</span>`,
      ``,
      `<span class="kw">export</span> <span class="kw">fn</span> <span class="fn-t">skills</span><span class="punc-t">():</span> <span class="kw">void</span> <span class="punc-t">{</span>`,
      ``,
      `  <span class="cmt-t">// ── Programming Languages ──────────────────────</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"Languages:  Python, C, C++, Java, C#, SQL, PL/SQL"</span><span class="punc-t">);</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"            JavaScript, TypeScript"</span><span class="punc-t">);</span>`,
      ``,
      `  <span class="cmt-t">// ── Web ────────────────────────────────────────</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"Web:        HTML, CSS, Tailwind"</span><span class="punc-t">);</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"            React, Next.js 15, Node.js, Express.js, Vercel"</span><span class="punc-t">);</span>`,
      ``,
      `  <span class="cmt-t">// ── Databases ──────────────────────────────────</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"Databases:  MySQL, PostgreSQL, MongoDB"</span><span class="punc-t">);</span>`,
      ``,
      `  <span class="cmt-t">// ── Systems & Desktop ──────────────────────────</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"Systems:    C, C++, Linux"</span><span class="punc-t">);</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"Desktop:    .NET / C#, PyQt5"</span><span class="punc-t">);</span>`,
      ``,
      `  <span class="cmt-t">// ── Compilers & AI — FYP focus ─────────────────</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"Compilers:  Flex, Bison → AST generation"</span><span class="punc-t">);</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"AI:         Azure AI Vision (image recognition)"</span><span class="punc-t">);</span>`,
      ``,
      `  <span class="cmt-t">// ── Networking & Tools ─────────────────────────</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"Network:    CCNA 1 Certified"</span><span class="punc-t">);</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"Tools:      Git, GitHub"</span><span class="punc-t">);</span>`,
      ``,
      `<span class="punc-t">}</span>`,
    ],
  },

  // ── experience.src ────────────────────────────────────────────────────────
  experience: {
    name: "experience.src",
    lang: "SourceLang",
    icon: "src",
    lines: [
      `<span class="str-t">"server"</span><span class="punc-t">;</span>`,
      ``,
      `<span class="kw">export</span> <span class="kw">fn</span> <span class="fn-t">experience</span><span class="punc-t">():</span> <span class="kw">void</span> <span class="punc-t">{</span>`,
      ``,
      `  <span class="cmt-t">// ── Internship — YottaByte ─────────────────────</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"[Internship] YottaByte — Monastir, Tunisia"</span><span class="punc-t">);</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"[Period]     July 2025 – August 2025"</span><span class="punc-t">);</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"[Mission]    Web app integrating 6–10 external APIs"</span><span class="punc-t">);</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"[Stack]      Next.js 15, Express.js, TypeScript"</span><span class="punc-t">);</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"[Tasks]      Customizable dashboard UI"</span><span class="punc-t">);</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"             Express backend — public API integration &amp; data viz"</span><span class="punc-t">);</span>`,
      ``,
      `  <span class="cmt-t">// ── Final Year Project — ISIMM Monastir ────────</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"[FYP]        ISIMM Monastir — Tunisia"</span><span class="punc-t">);</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"[Period]     January 2025 – June 2025"</span><span class="punc-t">);</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"[Mission]    Fullstack programming language dedicated to the web"</span><span class="punc-t">);</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"[Stack]      C, Flex, Bison, AST generation"</span><span class="punc-t">);</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"[Tasks]      Flex/Bison transpiler → AST → web code — Excellent grade"</span><span class="punc-t">);</span>`,
      ``,
      `  <span class="cmt-t">// ── Internship — WebProSoft ────────────────────</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"[Internship] WebProSoft — Monastir, Tunisia"</span><span class="punc-t">);</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"[Period]     June 2024 – July 2024"</span><span class="punc-t">);</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"[Mission]    Desktop/Web image recognition platform"</span><span class="punc-t">);</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"[Stack]      .NET C#, HTML/JS, Azure AI Models"</span><span class="punc-t">);</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"[Tasks]      Intuitive UI + Azure AI Vision integration — Excellent grade"</span><span class="punc-t">);</span>`,
      ``,
      `  <span class="cmt-t">// ── Freelance ──────────────────────────────────</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"[Freelance]  Independent client — Remote, Tunisia"</span><span class="punc-t">);</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"[Period]     January 2024 – March 2024"</span><span class="punc-t">);</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"[Mission]    Desktop application — business management"</span><span class="punc-t">);</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"[Stack]      Python, PyQt5, MySQL"</span><span class="punc-t">);</span>`,
      ``,
      `  <span class="cmt-t">// ── Academic Project — ISIMM ───────────────────</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"[Academic]   ISIMM Monastir — Tunisia"</span><span class="punc-t">);</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"[Period]     January 2023 – March 2023"</span><span class="punc-t">);</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"[Mission]    Patient records &amp; disease management application"</span><span class="punc-t">);</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"[Stack]      Python, PyQt5, MySQL, SQL"</span><span class="punc-t">);</span>`,
      ``,
      `<span class="punc-t">}</span>`,
    ],
  },

  // ── projects.src ──────────────────────────────────────────────────────────
  projects: {
    name: "projects.src",
    lang: "SourceLang",
    icon: "src",
    lines: [
      `<span class="str-t">"server"</span><span class="punc-t">;</span>`,
      ``,
      `<span class="kw">export</span> <span class="kw">fn</span> <span class="fn-t">projects</span><span class="punc-t">():</span> <span class="kw">void</span> <span class="punc-t">{</span>`,
      ``,
      `  <span class="cmt-t">// ── Open-Dash — YottaByte Internship ───────────</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"🌐 Open-Dash (Live Data Platform)"</span><span class="punc-t">);</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"[Context]  Internship — YottaByte, Monastir"</span><span class="punc-t">);</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"[Period]   July – August 2025"</span><span class="punc-t">);</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"[Stack]    Next.js 15, Leaflet, Chart.js, Express"</span><span class="punc-t">);</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"[Demo]     https://opendash.vercel.app"</span><span class="punc-t">);</span>`,
      ``,
      `  <span class="cmt-t">// ── SourceLang — Final Year Project ISIMM ──────</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"⚙️  SourceLang (my own programming language)"</span><span class="punc-t">);</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"[Context]  FYP — ISIMM Monastir — Excellent grade"</span><span class="punc-t">);</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"[Period]   January – June 2025"</span><span class="punc-t">);</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"[Stack]    C, Flex, Bison, AST → web code generation"</span><span class="punc-t">);</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"[Note]     This very file is written in SourceLang!"</span><span class="punc-t">);</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"[Docs]     https://sourcelang.vercel.app"</span><span class="punc-t">);</span>`,
      ``,
      `  <span class="cmt-t">// ── Analytics Dashboard ─────────────────────────</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"📊 Internship Analytics Dashboard"</span><span class="punc-t">);</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"[Context]  Personal project"</span><span class="punc-t">);</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"[Stack]    Next.js, TypeScript, MongoDB"</span><span class="punc-t">);</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"[Features] Upload Excel, Parse, Filter, Export JSON, Visualize, Analyze"</span><span class="punc-t">);</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"[Demo]     https://pfe-internship-isimm.netlify.app/dashboard"</span><span class="punc-t">);</span>`,
      ``,
      `  <span class="cmt-t">// ── Image Recognition — WebProSoft ──────────────</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"🤖 Image Recognition Platform"</span><span class="punc-t">);</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"[Context]  Internship — WebProSoft, Monastir"</span><span class="punc-t">);</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"[Period]   June – July 2024"</span><span class="punc-t">);</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"[Stack]    .NET C#, HTML/JS, Azure AI Models"</span><span class="punc-t">);</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"[Grade]    Excellent"</span><span class="punc-t">);</span>`,
      ``,
      `  <span class="cmt-t">// ── GitHub ─────────────────────────────────────</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"🔗 github.com/MalikaLaouiti"</span><span class="punc-t">);</span>`,
      ``,
      `<span class="punc-t">}</span>`,
    ],
  },

  // ── demos.mdx ─────────────────────────────────────────────────────────────
  demos: {
    name: "demos.mdx",
    lang: "SourceLang",
    icon: "mdx",
    demos: DEMO_PROJECTS,
    lines: [
      `<span class="str-t">"component"</span><span class="punc-t">;</span>`,
      ``,
      `<span class="kw2">import</span> <span class="type-t">DemoCard</span> <span class="kw2">from</span> <span class="str-t">"sourcelang/ui"</span><span class="punc-t">;</span>`,
      ``,
      `<span class="cmt-t">/**</span>`,
      `<span class="cmt-t"> * LIVE DEMOS</span>`,
      `<span class="cmt-t"> * Deployed projects — click to preview or open</span>`,
      `<span class="cmt-t"> */</span>`,
      ``,
      `<span class="kw">component</span> <span class="fn-t">DemosPage</span><span class="punc-t">() {</span>`,
      `  <span class="kw2">return</span> <span class="punc-t">(</span>`,
      `    <span class="punc-t">&lt;</span><span class="type-t">main</span><span class="punc-t">&gt;</span>`,
      ``,
      `      <span class="cmt-t">{/* ─── LIVE — Open-Dash ─── */}</span>`,
      `      <span class="punc-t">&lt;</span><span class="type-t">DemoCard</span>`,
      `        <span class="prop-t">title</span><span class="op-t">=</span><span class="str-t">"🌐 Open-Dash"</span>`,
      `        <span class="prop-t">url</span><span class="op-t">=</span><span class="str-t">"https://opendash.vercel.app"</span>`,
      `        <span class="prop-t">badge</span><span class="op-t">=</span><span class="str-t">"LIVE"</span>`,
      `      <span class="punc-t">/&gt;</span>`,
      ``,
      `      <span class="cmt-t">{/* ─── LIVE — SourceLang ─── */}</span>`,
      `      <span class="punc-t">&lt;</span><span class="type-t">DemoCard</span>`,
      `        <span class="prop-t">title</span><span class="op-t">=</span><span class="str-t">"⚙️  SourceLang"</span>`,
      `        <span class="prop-t">url</span><span class="op-t">=</span><span class="str-t">"https://sourcelang.vercel.app"</span>`,
      `        <span class="prop-t">badge</span><span class="op-t">=</span><span class="str-t">"LIVE"</span>`,
      `      <span class="punc-t">/&gt;</span>`,
      ``,
      `      <span class="cmt-t">{/* ─── LIVE — Analytics Dashboard ─── */}</span>`,
      `      <span class="punc-t">&lt;</span><span class="type-t">DemoCard</span>`,
      `        <span class="prop-t">title</span><span class="op-t">=</span><span class="str-t">"📊 Internship Analytics Dashboard"</span>`,
      `        <span class="prop-t">url</span><span class="op-t">=</span><span class="str-t">"https://pfe-internship-isimm.netlify.app/dashboard"</span>`,
      `        <span class="prop-t">badge</span><span class="op-t">=</span><span class="str-t">"LIVE"</span>`,
      `      <span class="punc-t">/&gt;</span>`,
      ``,
      `      <span class="cmt-t">{/* ─── GitHub — Image Recognition ─── */}</span>`,
      `      <span class="punc-t">&lt;</span><span class="type-t">DemoCard</span>`,
      `        <span class="prop-t">title</span><span class="op-t">=</span><span class="str-t">"🤖 Image Recognition (Azure AI)"</span>`,
      `        <span class="prop-t">url</span><span class="op-t">=</span><span class="str-t">"https://github.com/MalikaLaouiti"</span>`,
      `        <span class="prop-t">badge</span><span class="op-t">=</span><span class="str-t">"GitHub"</span>`,
      `      <span class="punc-t">/&gt;</span>`,
      ``,
      `    <span class="punc-t">&lt;/</span><span class="type-t">main</span><span class="punc-t">&gt;</span>`,
      `  <span class="punc-t">);</span>`,
      `<span class="punc-t">}</span>`,
    ],
  },

 
  documents: {
    name: "documents.src",
    lang: "SourceLang",
    icon: "pdf",   
    lines: [
      `<span class="str-t">"server"</span><span class="punc-t">;</span>`,
      ``,
      `<span class="kw">export</span> <span class="kw">fn</span> <span class="fn-t">documents</span><span class="punc-t">():</span> <span class="kw">void</span> <span class="punc-t">{</span>`,
      ``,
      `  <span class="cmt-t">// ── CV ──────────────────────────────────────────</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"[CV]        CV-MalikaLaouiti.pdf"</span><span class="punc-t">);</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"[Year]      2025"</span><span class="punc-t">);</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"[Status]    available ✓"</span><span class="punc-t">);</span>`,
      ``,
      `  <span class="cmt-t">// ── Internship Certificates ─────────────────────</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"[Attest.]   YottaByte — July–August 2025"</span><span class="punc-t">);</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"[Company]   YottaByte, Monastir"</span><span class="punc-t">);</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"[Status]    available ✓"</span><span class="punc-t">);</span>`,
      ``,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"[Attest.]   WebProSoft — June–July 2024"</span><span class="punc-t">);</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"[Company]   WebProSoft, Monastir"</span><span class="punc-t">);</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"[Status]    available ✓"</span><span class="punc-t">);</span>`,
      ``,
      `  <span class="cmt-t">// ── Professional Certificate ─────────────────────</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"[Cert.]     CCNA 1 — Introduction to Networks"</span><span class="punc-t">);</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"[Issuer]    Cisco Networking Academy"</span><span class="punc-t">);</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"[Status]    available ✓"</span><span class="punc-t">);</span>`,
      ``,
      `  <span class="cmt-t">// ── Degrees ─────────────────────────────────────</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"[Degree]    BSc GL & SI — ISIMM Monastir"</span><span class="punc-t">);</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"[Mention]   Excellent (FYP: SourceLang)"</span><span class="punc-t">);</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"[Year]      2025"</span><span class="punc-t">);</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"[Status]    available ✓"</span><span class="punc-t">);</span>`,
      ``,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"[Bac]       Bac Technologique — Ibn Khaldoun Jemmel"</span><span class="punc-t">);</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"[Grade]     15.73 / 20"</span><span class="punc-t">);</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"[Year]      2022"</span><span class="punc-t">);</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"[Status]    available ✓"</span><span class="punc-t">);</span>`,
      ``,
      `  <span class="cmt-t">// ── Transcript ──────────────────────────────────</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"[Transcript] BSc ISIMM (2022–2025)"</span><span class="punc-t">);</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"[Status]     on-request — contact laouiti.malika@yahoo.com"</span><span class="punc-t">);</span>`,
      ``,
      `<span class="punc-t">}</span>`,
    ],
  },

  // ── contact.src ───────────────────────────────────────────────────────────
  contact: {
    name: "contact.src",
    lang: "SourceLang",
    icon: "src",
    lines: [
      `<span class="str-t">"server"</span><span class="punc-t">;</span>`,
      ``,
      `<span class="kw">export</span> <span class="kw">fn</span> <span class="fn-t">contact</span><span class="punc-t">():</span> <span class="kw">void</span> <span class="punc-t">{</span>`,
      ``,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"Email:    laouiti.malika@yahoo.com"</span><span class="punc-t">);</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"Phone:    +216 25 731 613"</span><span class="punc-t">);</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"GitHub:   github.com/MalikaLaouiti"</span><span class="punc-t">);</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"LinkedIn: linkedin.com/in/malika-laouiti"</span><span class="punc-t">);</span>`,
      `  <span class="fn-t">printf</span><span class="punc-t">(</span><span class="str-t">"Location: Cité El Feth, Jemmel, Monastir 5020 🇹🇳"</span><span class="punc-t">);</span>`,
      ``,
      `  <span class="cmt-t">// available immediately — software / web / systems internship</span>`,
      ``,
      `<span class="punc-t">}</span>`,
    ],
  },

  // ── package.json ──────────────────────────────────────────────────────────
  config: {
    name: "package.json",
    lang: "JSON",
    icon: "json",
    lines: [
      `<span class="punc-t">{</span>`,
      `  <span class="prop-t">"name"</span><span class="punc-t">:</span>        <span class="str-t">"malika-laouiti-portfolio"</span><span class="punc-t">,</span>`,
      `  <span class="prop-t">"version"</span><span class="punc-t">:</span>     <span class="str-t">"1.0.0"</span><span class="punc-t">,</span>`,
      `  <span class="prop-t">"author"</span><span class="punc-t">:</span>      <span class="str-t">"LAOUITI Malika"</span><span class="punc-t">,</span>`,
      `  <span class="prop-t">"description"</span><span class="punc-t">:</span> <span class="str-t">"Fullstack Developer &amp; Systems Engineer"</span><span class="punc-t">,</span>`,
      `  <span class="prop-t">"available"</span><span class="punc-t">:</span>   <span class="bool-t">true</span><span class="punc-t">,</span>`,
      `  <span class="prop-t">"lang"</span><span class="punc-t">:</span>        <span class="str-t">"SourceLang"</span><span class="punc-t">,</span>  <span class="cmt-t">// my own language (FYP)</span>`,
      `  <span class="prop-t">"education"</span><span class="punc-t">: {</span>`,
      `    <span class="prop-t">"current"</span><span class="punc-t">:</span>  <span class="str-t">"Software Engineering — ISSAT Sousse (2025–present)"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">"degree"</span><span class="punc-t">:</span>   <span class="str-t">"BSc Software Engineering — ISIMM Monastir (2025)"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">"cert"</span><span class="punc-t">:</span>     <span class="str-t">"CCNA 1"</span>`,
      `  <span class="punc-t">},</span>`,
      `  <span class="prop-t">"scripts"</span><span class="punc-t">: {</span>`,
      `    <span class="prop-t">"demo"</span><span class="punc-t">:</span>    <span class="str-t">"open https://opendash.vercel.app"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">"github"</span><span class="punc-t">:</span>  <span class="str-t">"open github.com/MalikaLaouiti"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">"contact"</span><span class="punc-t">:</span> <span class="str-t">"mailto:Laouiti.malika@yahoo.com"</span>`,
      `  <span class="punc-t">},</span>`,
      `  <span class="prop-t">"stack"</span><span class="punc-t">: {</span>`,
      `    <span class="prop-t">"web"</span><span class="punc-t">:</span>     <span class="punc-t">[</span><span class="str-t">"React"</span><span class="punc-t">,</span> <span class="str-t">"Next.js 15"</span><span class="punc-t">,</span> <span class="str-t">"TypeScript"</span><span class="punc-t">,</span> <span class="str-t">"Tailwind"</span><span class="punc-t">],</span>`,
      `    <span class="prop-t">"backend"</span><span class="punc-t">:</span> <span class="punc-t">[</span><span class="str-t">"Node.js"</span><span class="punc-t">,</span> <span class="str-t">"Express.js"</span><span class="punc-t">,</span> <span class="str-t">"MySQL"</span><span class="punc-t">,</span> <span class="str-t">"PostgreSQL"</span><span class="punc-t">,</span> <span class="str-t">"MongoDB"</span><span class="punc-t">],</span>`,
      `    <span class="prop-t">"systems"</span><span class="punc-t">:</span> <span class="punc-t">[</span><span class="str-t">"C"</span><span class="punc-t">,</span> <span class="str-t">"C++"</span><span class="punc-t">,</span> <span class="str-t">"Linux"</span><span class="punc-t">,</span> <span class="str-t">"Flex/Bison"</span><span class="punc-t">,</span> <span class="str-t">"Azure AI"</span><span class="punc-t">],</span>`,
      `    <span class="prop-t">"desktop"</span><span class="punc-t">:</span> <span class="punc-t">[</span><span class="str-t">"Python/PyQt5"</span><span class="punc-t">,</span> <span class="str-t">".NET C#"</span><span class="punc-t">]</span>`,
      `  <span class="punc-t">}</span>`,
      `<span class="punc-t">}</span>`,
    ],
  },
};

export const FILE_KEYS: FileKey[] = [
  "about", "skills", "experience", "projects",
  "demos", "documents", "contact", "config",
];