export type FileKey =
  | "about"
  | "skills"
  | "experience"
  | "projects"
  | "demos"
  | "contact"
  | "config";

export interface DemoProject {
  id: string;
  title: string;
  desc: string;
  url: string;
  repo: string;
  stack: string[];
  badge: "LIVE" | "GitHub" | "WIP";
  thumb?: string;
}

export interface FileData {
  name: string;
  lang: string;
  icon: "ts" | "json" | "mdx" | "pdf";
  lines: string[];
  demos?: DemoProject[];
}

// ─── DEMO PROJECTS DATA ─────────────────────────────────────────────────────
export const DEMO_PROJECTS: DemoProject[] = [
  {
    id: "opendash",
    title: "🌐 Open-Dash",
    desc: "Live dashboard — météo, cartes Leaflet, données géo temps réel",
    url: "https://opendash.vercel.app",
    repo: "https://github.com/MalikaLaouiti",
    stack: ["Next.js 15", "Leaflet", "Chart.js", "Express API"],
    badge: "LIVE",
  },
  {
    id: "sourcelang",
    title: "⚙️ SourceLang",
    desc: "Transpilateur custom — mon propre langage de programmation FullStack (PFE 2025)",
    url: "https://sourcelang.vercel.app",
    repo: "https://github.com/MalikaLaouiti",
    stack: ["C", "Flex", "Bison", "AST"],
    badge: "LIVE",
  },
  {
    id: "exceldash",
    title: "📊 Dashboard d'Analyse Stage Académique",
    desc: "Upload Excel, parsing, filtrage, export JSON — pipeline data visuel",
    url: "https://pfe-internship-isimm.netlify.app/dashboard",
    repo: "https://github.com/MalikaLaouiti",
    stack: ["Next.js", "TypeScript", "MongoDB"],
    badge: "LIVE",
  },
  {
    id: "imgrecog",
    title: "🤖 Image Recognition",
    desc: "App Desktop/Web C#.NET — reconnaissance d'images Azure AI temps réel",
    url: "https://github.com/MalikaLaouiti",
    repo: "https://github.com/MalikaLaouiti",
    stack: [".NET C#", "HTML/JS", "Azure AI"],
    badge: "GitHub",
  },
];

export const FILES: Record<FileKey, FileData> = {

  // ── about.ts ──────────────────────────────────────────────────────────────
  about: {
    name: "about.ts",
    lang: "TypeScript",
    icon: "ts",
    lines: [
      `<span class="kw2">import</span> <span class="kw">type</span> <span class="punc-t">{</span> <span class="type-t">Developer</span> <span class="punc-t">}</span> <span class="kw2">from</span> <span class="str-t">"./types"</span><span class="punc-t">;</span>`,
      ``,
      `<span class="kw">const</span> <span class="fn-t">about</span><span class="punc-t">:</span> <span class="type-t">Developer</span> <span class="op-t">=</span> <span class="punc-t">{</span>`,
      ``,
      `  <span class="prop-t">name</span><span class="punc-t">:</span>     <span class="str-t">"LAOUITI Malika"</span><span class="punc-t">,</span>`,
      `  <span class="prop-t">role</span><span class="punc-t">:</span>     <span class="str-t">"Développeuse Fullstack &amp; Systèmes"</span><span class="punc-t">,</span>`,
      ``,
      `  <span class="prop-t">formation</span><span class="punc-t">: {</span>`,
      `    <span class="prop-t">degree</span><span class="punc-t">:</span>  <span class="str-t">"Licence GL &amp; SI — ISIMM Monastir"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">year</span><span class="punc-t">:</span>    <span class="num-t">2025</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">bac</span><span class="punc-t">:</span>     <span class="str-t">"Bac Technologique — Ibn Khaldoun Jemmel"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">grade</span><span class="punc-t">:</span>   <span class="num-t">15.73</span> <span class="op-t">/</span> <span class="num-t">20</span><span class="punc-t">,</span>`,
      `  <span class="punc-t">},</span>`,
      ``,
      `  <span class="prop-t">status</span><span class="punc-t">: {</span>`,
      `    <span class="prop-t">seeking</span><span class="punc-t">:</span>   <span class="str-t">"stage — développement logiciel / web / systèmes"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">location</span><span class="punc-t">:</span>  <span class="str-t">"Monastir 5020 🇹🇳"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">available</span><span class="punc-t">:</span> <span class="bool-t">true</span><span class="punc-t">,</span>`,
      `  <span class="punc-t">},</span>`,
      ``,
      `<span class="punc-t">};</span>`,
      ``,
      `<span class="kw2">export default</span> <span class="fn-t">about</span><span class="punc-t">;</span>`,
    ],
  },

  // ── skills.ts ─────────────────────────────────────────────────────────────
  skills: {
    name: "skills.ts",
    lang: "TypeScript",
    icon: "ts",
    lines: [
      `<span class="kw2">export</span> <span class="kw">const</span> <span class="fn-t">skills</span> <span class="op-t">=</span> <span class="punc-t">{</span>`,
      ``,
      `  <span class="cmt-t">// ── Langages de programmation ──────────────────</span>`,
      `  <span class="prop-t">languages</span><span class="punc-t">:</span> <span class="punc-t">[</span>`,
      `    <span class="str-t">"Python"</span><span class="punc-t">,</span> <span class="str-t">"C"</span><span class="punc-t">,</span> <span class="str-t">"Java"</span><span class="punc-t">,</span> <span class="str-t">"C#"</span><span class="punc-t">,</span>`,
      `    <span class="str-t">"SQL"</span><span class="punc-t">,</span> <span class="str-t">"PL/SQL"</span><span class="punc-t">,</span> <span class="str-t">"JavaScript"</span><span class="punc-t">,</span> <span class="str-t">"TypeScript"</span><span class="punc-t">,</span>`,
      `  <span class="punc-t">],</span>`,
      ``,
      `  <span class="cmt-t">// ── Web ────────────────────────────────────────</span>`,
      `  <span class="prop-t">web</span><span class="punc-t">:</span> <span class="punc-t">[</span>`,
      `    <span class="str-t">"HTML"</span><span class="punc-t">,</span> <span class="str-t">"CSS"</span><span class="punc-t">,</span> <span class="str-t">"Tailwind"</span><span class="punc-t">,</span>`,
      `    <span class="str-t">"Next.js 15"</span><span class="punc-t">,</span> <span class="str-t">"Express.js"</span><span class="punc-t">,</span> <span class="str-t">"Vercel"</span><span class="punc-t">,</span>`,
      `  <span class="punc-t">],</span>`,
      ``,
      `  <span class="cmt-t">// ── Bases de données ───────────────────────────</span>`,
      `  <span class="prop-t">databases</span><span class="punc-t">:</span> <span class="punc-t">[</span><span class="str-t">"MySQL"</span><span class="punc-t">,</span> <span class="str-t">"PostgreSQL"</span><span class="punc-t">],</span>`,
      ``,
      `  <span class="cmt-t">// ── Desktop ────────────────────────────────────</span>`,
      `  <span class="prop-t">desktop</span><span class="punc-t">:</span> <span class="punc-t">[</span><span class="str-t">".NET / C#"</span><span class="punc-t">,</span> <span class="str-t">"PyQt5"</span><span class="punc-t">],</span>`,
      ``,
      `  <span class="cmt-t">// ── Outils spéciaux — mon PFE ──────────────────</span>`,
      `  <span class="prop-t">compilers</span><span class="punc-t">:</span> <span class="punc-t">[</span><span class="str-t">"Flex"</span><span class="punc-t">,</span> <span class="str-t">"Bison"</span><span class="punc-t">,</span> <span class="str-t">"AST generation"</span><span class="punc-t">],</span>`,
      `  <span class="prop-t">ai</span><span class="punc-t">:</span>        <span class="punc-t">[</span><span class="str-t">"Azure AI Vision"</span><span class="punc-t">],</span>`,
      `  <span class="prop-t">tools</span><span class="punc-t">:</span>     <span class="punc-t">[</span><span class="str-t">"Git"</span><span class="punc-t">,</span> <span class="str-t">"GitHub"</span><span class="punc-t">],</span>`,
      ``,
      `<span class="punc-t">}</span> <span class="kw">as const</span><span class="punc-t">;</span>`,
    ],
  },

  // ── experience.ts ─────────────────────────────────────────────────────────
  experience: {
    name: "experience.ts",
    lang: "TypeScript",
    icon: "ts",
    lines: [
      `<span class="kw2">import</span> <span class="kw">type</span> <span class="punc-t">{</span> <span class="type-t">Experience</span> <span class="punc-t">}</span> <span class="kw2">from</span> <span class="str-t">"./types"</span><span class="punc-t">;</span>`,
      ``,
      `<span class="kw2">export</span> <span class="kw">const</span> <span class="fn-t">experience</span><span class="punc-t">:</span> <span class="type-t">Experience</span><span class="punc-t">[]</span> <span class="op-t">=</span> <span class="punc-t">[</span>`,
      ``,
      `  <span class="cmt-t">// ── Stage — YottaByte ──────────────────────────</span>`,
      `  <span class="punc-t">{</span>`,
      `    <span class="prop-t">type</span><span class="punc-t">:</span>    <span class="str-t">"Stage"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">company</span><span class="punc-t">:</span> <span class="str-t">"YottaByte — Monastir, Tunisie"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">period</span><span class="punc-t">:</span>  <span class="str-t">"Juillet 2025 – Août 2025"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">mission</span><span class="punc-t">:</span> <span class="str-t">"App web intégrant 6-10 API externes"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">stack</span><span class="punc-t">:</span>   <span class="punc-t">[</span><span class="str-t">"Next.js 15"</span><span class="punc-t">,</span> <span class="str-t">"Express.js"</span><span class="punc-t">,</span> <span class="str-t">"TypeScript"</span><span class="punc-t">],</span>`,
      `    <span class="prop-t">tasks</span><span class="punc-t">:</span>   <span class="punc-t">[</span>`,
      `      <span class="str-t">"UI tableau de bord personnalisable"</span><span class="punc-t">,</span>`,
      `      <span class="str-t">"Backend Express — intégration API publiques"</span><span class="punc-t">,</span>`,
      `    <span class="punc-t">],</span>`,
      `  <span class="punc-t">},</span>`,
      ``,
      `  <span class="cmt-t">// ── PFE — ISIMM Monastir ───────────────────────</span>`,
      `  <span class="punc-t">{</span>`,
      `    <span class="prop-t">type</span><span class="punc-t">:</span>    <span class="str-t">"PFE"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">company</span><span class="punc-t">:</span> <span class="str-t">"ISIMM Monastir — Tunisie"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">period</span><span class="punc-t">:</span>  <span class="str-t">"Janvier 2025 – Juin 2025"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">mission</span><span class="punc-t">:</span> <span class="str-t">"Langage de programmation FullStack dédié web"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">stack</span><span class="punc-t">:</span>   <span class="punc-t">[</span><span class="str-t">"C"</span><span class="punc-t">,</span> <span class="str-t">"Flex"</span><span class="punc-t">,</span> <span class="str-t">"Bison"</span><span class="punc-t">,</span> <span class="str-t">"AST generation"</span><span class="punc-t">],</span>`,
      `    <span class="prop-t">tasks</span><span class="punc-t">:</span>   <span class="punc-t">[</span><span class="str-t">"Transpilateur Flex/Bison → AST → code web"</span><span class="punc-t">],</span>`,
      `  <span class="punc-t">},</span>`,
      ``,
      `  <span class="cmt-t">// ── Stage — WebProSoft ─────────────────────────</span>`,
      `  <span class="punc-t">{</span>`,
      `    <span class="prop-t">type</span><span class="punc-t">:</span>    <span class="str-t">"Stage"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">company</span><span class="punc-t">:</span> <span class="str-t">"WebProSoft — Monastir, Tunisie"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">period</span><span class="punc-t">:</span>  <span class="str-t">"Juin 2024 – Juillet 2024"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">mission</span><span class="punc-t">:</span> <span class="str-t">"Plateforme Desktop/Web reconnaissance d'images"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">stack</span><span class="punc-t">:</span>   <span class="punc-t">[</span><span class="str-t">".NET C#"</span><span class="punc-t">,</span> <span class="str-t">"HTML/JS"</span><span class="punc-t">,</span> <span class="str-t">"Azure AI Models"</span><span class="punc-t">],</span>`,
      `    <span class="prop-t">tasks</span><span class="punc-t">:</span>   <span class="punc-t">[</span><span class="str-t">"Interface intuitive + Azure AI Vision"</span><span class="punc-t">],</span>`,
      `  <span class="punc-t">},</span>`,
      ``,
      `  <span class="cmt-t">// ── Freelance ──────────────────────────────────</span>`,
      `  <span class="punc-t">{</span>`,
      `    <span class="prop-t">type</span><span class="punc-t">:</span>    <span class="str-t">"Freelance"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">company</span><span class="punc-t">:</span> <span class="str-t">"Client indépendant — Remote, Tunisie"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">period</span><span class="punc-t">:</span>  <span class="str-t">"Janvier 2024 – Mars 2024"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">mission</span><span class="punc-t">:</span> <span class="str-t">"Application desktop — gestion d'entreprise"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">stack</span><span class="punc-t">:</span>   <span class="punc-t">[</span><span class="str-t">"Python"</span><span class="punc-t">,</span> <span class="str-t">"PyQt5"</span><span class="punc-t">,</span> <span class="str-t">"MySQL"</span><span class="punc-t">],</span>`,
      `  <span class="punc-t">},</span>`,
      ``,
      `  <span class="cmt-t">// ── Projet académique — ISIMM ──────────────────</span>`,
      `  <span class="punc-t">{</span>`,
      `    <span class="prop-t">type</span><span class="punc-t">:</span>    <span class="str-t">"Académique"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">company</span><span class="punc-t">:</span> <span class="str-t">"ISIMM Monastir — Tunisie"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">period</span><span class="punc-t">:</span>  <span class="str-t">"Janvier 2023 – Mars 2023"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">mission</span><span class="punc-t">:</span> <span class="str-t">"App gestion des maladies — archivage patients"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">stack</span><span class="punc-t">:</span>   <span class="punc-t">[</span><span class="str-t">"Python"</span><span class="punc-t">,</span> <span class="str-t">"PyQt5"</span><span class="punc-t">,</span> <span class="str-t">"MySQL"</span><span class="punc-t">,</span> <span class="str-t">"SQL"</span><span class="punc-t">],</span>`,
      `  <span class="punc-t">},</span>`,
      ``,
      `<span class="punc-t">];</span>`,
    ],
  },

  // ── projects.ts ───────────────────────────────────────────────────────────
  projects: {
    name: "projects.ts",
    lang: "TypeScript",
    icon: "ts",
    lines: [
      `<span class="kw2">import</span> <span class="kw">type</span> <span class="punc-t">{</span> <span class="type-t">Project</span> <span class="punc-t">}</span> <span class="kw2">from</span> <span class="str-t">"./types"</span><span class="punc-t">;</span>`,
      ``,
      `<span class="kw2">export</span> <span class="kw">const</span> <span class="fn-t">projects</span><span class="punc-t">:</span> <span class="type-t">Project</span><span class="punc-t">[]</span> <span class="op-t">=</span> <span class="punc-t">[</span>`,
      ``,
      `  <span class="cmt-t">// ── Open-Dash — Stage YottaByte ────────────────</span>`,
      `  <span class="punc-t">{</span>`,
      `    <span class="prop-t">title</span><span class="punc-t">:</span>   <span class="str-t">"🌐 Open-Dash (Live Data Platform)"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">context</span><span class="punc-t">:</span> <span class="str-t">"Stage — YottaByte, Monastir"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">period</span><span class="punc-t">:</span>  <span class="str-t">"Juillet – Août 2025"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">stack</span><span class="punc-t">:</span>   <span class="punc-t">[</span><span class="str-t">"Next.js 15"</span><span class="punc-t">,</span> <span class="str-t">"Leaflet"</span><span class="punc-t">,</span> <span class="str-t">"Chart.js"</span><span class="punc-t">,</span> <span class="str-t">"Express"</span><span class="punc-t">],</span>`,
      `    <span class="prop-t">demo</span><span class="punc-t">:</span>    <span class="str-t">"https://opendash.vercel.app"</span><span class="punc-t">,</span>`,
      `  <span class="punc-t">},</span>`,
      ``,
      `  <span class="cmt-t">// ── SourceLang — PFE ISIMM ─────────────────────</span>`,
      `  <span class="punc-t">{</span>`,
      `    <span class="prop-t">title</span><span class="punc-t">:</span>   <span class="str-t">"⚙️  SourceLang (mon propre langage)"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">context</span><span class="punc-t">:</span> <span class="str-t">"PFE — ISIMM Monastir"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">period</span><span class="punc-t">:</span>  <span class="str-t">"Janvier – Juin 2025"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">stack</span><span class="punc-t">:</span>   <span class="punc-t">[</span><span class="str-t">"C"</span><span class="punc-t">,</span> <span class="str-t">"Flex"</span><span class="punc-t">,</span> <span class="str-t">"Bison"</span><span class="punc-t">,</span> <span class="str-t">"AST → code web"</span><span class="punc-t">],</span>`,
      `    <span class="prop-t">note</span><span class="punc-t">:</span>    <span class="str-t">"Ce fichier est écrit en SourceLang !"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">docs</span><span class="punc-t">:</span>    <span class="str-t">"https://sourcelang.vercel.app"</span><span class="punc-t">,</span>`,
      `  <span class="punc-t">},</span>`,
      ``,
      `  <span class="cmt-t">// ── Excel Dashboard — Projet perso ─────────────</span>`,
      `  <span class="punc-t">{</span>`,
      `    <span class="prop-t">title</span><span class="punc-t">:</span>    <span class="str-t">"📊 Dashboard d'Analyse Stage Académique"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">context</span><span class="punc-t">:</span>  <span class="str-t">"Projet personnel"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">stack</span><span class="punc-t">:</span>    <span class="punc-t">[</span><span class="str-t">"Next.js"</span><span class="punc-t">,</span> <span class="str-t">"TypeScript"</span><span class="punc-t">,</span> <span class="str-t">"MongoDB"</span><span class="punc-t">],</span>`,
      `    <span class="prop-t">features</span><span class="punc-t">:</span> <span class="punc-t">[</span>`,
      `      <span class="str-t">"Upload Excel"</span><span class="punc-t">,</span> <span class="str-t">"Parse"</span><span class="punc-t">,</span> <span class="str-t">"Filter"</span><span class="punc-t">,</span>`,
      `      <span class="str-t">"Export JSON"</span><span class="punc-t">,</span> <span class="str-t">"Visualisation"</span><span class="punc-t">,</span> <span class="str-t">"Analyse Données"</span><span class="punc-t">,</span>`,
      `    <span class="punc-t">],</span>`,
      `    <span class="prop-t">demo</span><span class="punc-t">:</span>     <span class="str-t">"https://pfe-internship-isimm.netlify.app/dashboard"</span><span class="punc-t">,</span>`,
      `  <span class="punc-t">},</span>`,
      ``,
      `  <span class="cmt-t">// ── Image Recognition — Stage WebProSoft ───────</span>`,
      `  <span class="punc-t">{</span>`,
      `    <span class="prop-t">title</span><span class="punc-t">:</span>   <span class="str-t">"🤖 Image Recognition Platform"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">context</span><span class="punc-t">:</span> <span class="str-t">"Stage — WebProSoft, Monastir"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">period</span><span class="punc-t">:</span>  <span class="str-t">"Juin – Juillet 2024"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">stack</span><span class="punc-t">:</span>   <span class="punc-t">[</span><span class="str-t">".NET C#"</span><span class="punc-t">,</span> <span class="str-t">"HTML/JS"</span><span class="punc-t">,</span> <span class="str-t">"Azure AI Models"</span><span class="punc-t">],</span>`,
      `  <span class="punc-t">},</span>`,
      ``,
      `<span class="punc-t">];</span>`,
      ``,
      `<span class="cmt-t">// 🔗 github.com/MalikaLaouiti</span>`,
    ],
  },

  // ── demos.tsx ─────────────────────────────────────────────────────────────
  demos: {
    name: "demos.tsx",
    lang: "TypeScript",
    icon: "mdx",
    demos: DEMO_PROJECTS,
    lines: [
      `<span class="kw2">import</span> <span class="type-t">React</span> <span class="kw2">from</span> <span class="str-t">"react"</span><span class="punc-t">;</span>`,
      `<span class="kw2">import</span> <span class="punc-t">{</span> <span class="type-t">DemoCard</span> <span class="punc-t">}</span> <span class="kw2">from</span> <span class="str-t">"@/components/ui"</span><span class="punc-t">;</span>`,
      `<span class="kw2">import</span> <span class="kw">type</span> <span class="punc-t">{</span> <span class="type-t">DemoProject</span> <span class="punc-t">}</span> <span class="kw2">from</span> <span class="str-t">"./types"</span><span class="punc-t">;</span>`,
      ``,
      `<span class="cmt-t">/**</span>`,
      `<span class="cmt-t"> * DÉMOS EN LIGNE</span>`,
      `<span class="cmt-t"> * Projets déployés — cliquer pour prévisualiser ou ouvrir</span>`,
      `<span class="cmt-t"> */</span>`,
      ``,
      `<span class="kw">const</span> <span class="fn-t">DemosPage</span><span class="punc-t">:</span> <span class="type-t">React.FC</span> <span class="op-t">=</span> <span class="punc-t">() =&gt; {</span>`,
      `  <span class="kw2">return</span> <span class="punc-t">(</span>`,
      `    <span class="punc-t">&lt;</span><span class="type-t">main</span><span class="punc-t">&gt;</span>`,
      ``,
      `      <span class="cmt-t">{/* ─── LIVE — Open-Dash ─── */}</span>`,
      `      <span class="punc-t">&lt;</span><span class="type-t">DemoCard</span>`,
      `        <span class="prop-t">title</span><span class="op-t">=</span><span class="str-t">"🌐 Open-Dash"</span>`,
      `        <span class="prop-t">url</span><span class="op-t">=</span><span class="str-t">"https://opendash.vercel.app"</span>`,
      `        <span class="prop-t">badge</span><span class="op-t">=</span><span class="str-t">"LIVE"</span>`,
      `      <span class="punc-t">/&gt;</span>`,
      ``,
      `      <span class="cmt-t">{/* ─── LIVE — SourceLang ─── */}</span>`,
      `      <span class="punc-t">&lt;</span><span class="type-t">DemoCard</span>`,
      `        <span class="prop-t">title</span><span class="op-t">=</span><span class="str-t">"⚙️  SourceLang"</span>`,
      `        <span class="prop-t">url</span><span class="op-t">=</span><span class="str-t">"https://sourcelang.vercel.app"</span>`,
      `        <span class="prop-t">badge</span><span class="op-t">=</span><span class="str-t">"LIVE"</span>`,
      `      <span class="punc-t">/&gt;</span>`,
      ``,
      `      <span class="cmt-t">{/* ─── LIVE — Excel Dashboard ─── */}</span>`,
      `      <span class="punc-t">&lt;</span><span class="type-t">DemoCard</span>`,
      `        <span class="prop-t">title</span><span class="op-t">=</span><span class="str-t">"📊 Dashboard d'Analyse Stage Académique"</span>`,
      `        <span class="prop-t">url</span><span class="op-t">=</span><span class="str-t">"https://pfe-internship-isimm.netlify.app/dashboard"</span>`,
      `        <span class="prop-t">badge</span><span class="op-t">=</span><span class="str-t">"LIVE"</span>`,
      `      <span class="punc-t">/&gt;</span>`,
      ``,
      `      <span class="cmt-t">{/* ─── GitHub — Image Recognition ─── */}</span>`,
      `      <span class="punc-t">&lt;</span><span class="type-t">DemoCard</span>`,
      `        <span class="prop-t">title</span><span class="op-t">=</span><span class="str-t">"🤖 Image Recognition (Azure AI)"</span>`,
      `        <span class="prop-t">url</span><span class="op-t">=</span><span class="str-t">"https://github.com/MalikaLaouiti"</span>`,
      `        <span class="prop-t">badge</span><span class="op-t">=</span><span class="str-t">"GitHub"</span>`,
      `      <span class="punc-t">/&gt;</span>`,
      ``,
      `    <span class="punc-t">&lt;/</span><span class="type-t">main</span><span class="punc-t">&gt;</span>`,
      `  <span class="punc-t">);</span>`,
      `<span class="punc-t">};</span>`,
      ``,
      `<span class="kw2">export default</span> <span class="fn-t">DemosPage</span><span class="punc-t">;</span>`,
    ],
  },

  // ── contact.ts ────────────────────────────────────────────────────────────
  contact: {
    name: "contact.ts",
    lang: "TypeScript",
    icon: "ts",
    lines: [
      `<span class="kw2">import</span> <span class="kw">type</span> <span class="punc-t">{</span> <span class="type-t">ContactInfo</span> <span class="punc-t">}</span> <span class="kw2">from</span> <span class="str-t">"./types"</span><span class="punc-t">;</span>`,
      ``,
      `<span class="kw2">export</span> <span class="kw">const</span> <span class="fn-t">contact</span><span class="punc-t">:</span> <span class="type-t">ContactInfo</span> <span class="op-t">=</span> <span class="punc-t">{</span>`,
      ``,
      `  <span class="prop-t">email</span><span class="punc-t">:</span>    <span class="str-t">"laouiti.malika@yahoo.com"</span><span class="punc-t">,</span>`,
      `  <span class="prop-t">phone</span><span class="punc-t">:</span>    <span class="str-t">"+216 25 731 613"</span><span class="punc-t">,</span>`,
      `  <span class="prop-t">github</span><span class="punc-t">:</span>   <span class="str-t">"github.com/MalikaLaouiti"</span><span class="punc-t">,</span>`,
      `  <span class="prop-t">linkedin</span><span class="punc-t">:</span> <span class="str-t">"linkedin.com/in/malika-laouiti"</span><span class="punc-t">,</span>`,
      `  <span class="prop-t">location</span><span class="punc-t">:</span> <span class="str-t">"Cité El Feth, Jemmel, Monastir 5020 🇹🇳"</span><span class="punc-t">,</span>`,
      ``,
      `  <span class="cmt-t">// disponible immédiatement — stage développement</span>`,
      `  <span class="prop-t">available</span><span class="punc-t">:</span> <span class="bool-t">true</span><span class="punc-t">,</span>`,
      ``,
      `<span class="punc-t">};</span>`,
    ],
  },

  // ── package.json ──────────────────────────────────────────────────────────
  config: {
    name: "package.json",
    lang: "JSON",
    icon: "json",
    lines: [
      `<span class="punc-t">{</span>`,
      `  <span class="prop-t">"name"</span><span class="punc-t">:</span>        <span class="str-t">"malika-laouiti-portfolio"</span><span class="punc-t">,</span>`,
      `  <span class="prop-t">"version"</span><span class="punc-t">:</span>     <span class="str-t">"1.0.0"</span><span class="punc-t">,</span>`,
      `  <span class="prop-t">"author"</span><span class="punc-t">:</span>      <span class="str-t">"LAOUITI Malika"</span><span class="punc-t">,</span>`,
      `  <span class="prop-t">"description"</span><span class="punc-t">:</span> <span class="str-t">"Développeuse Fullstack &amp; Systèmes"</span><span class="punc-t">,</span>`,
      `  <span class="prop-t">"available"</span><span class="punc-t">:</span>   <span class="bool-t">true</span><span class="punc-t">,</span>`,
      `  <span class="prop-t">"scripts"</span><span class="punc-t">: {</span>`,
      `    <span class="prop-t">"demo"</span><span class="punc-t">:</span>    <span class="str-t">"open https://opendash.vercel.app"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">"github"</span><span class="punc-t">:</span>  <span class="str-t">"open github.com/MalikaLaouiti"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">"contact"</span><span class="punc-t">:</span> <span class="str-t">"mailto:Laouiti.malika@yahoo.com"</span>`,
      `  <span class="punc-t">},</span>`,
      `  <span class="prop-t">"stack"</span><span class="punc-t">: {</span>`,
      `    <span class="prop-t">"web"</span><span class="punc-t">:</span>     <span class="punc-t">[</span><span class="str-t">"Next.js 15"</span><span class="punc-t">,</span> <span class="str-t">"TypeScript"</span><span class="punc-t">,</span> <span class="str-t">"Tailwind"</span><span class="punc-t">],</span>`,
      `    <span class="prop-t">"backend"</span><span class="punc-t">:</span> <span class="punc-t">[</span><span class="str-t">"Express.js"</span><span class="punc-t">,</span> <span class="str-t">"MySQL"</span><span class="punc-t">,</span> <span class="str-t">"PostgreSQL"</span><span class="punc-t">],</span>`,
      `    <span class="prop-t">"systems"</span><span class="punc-t">:</span> <span class="punc-t">[</span><span class="str-t">"C"</span><span class="punc-t">,</span> <span class="str-t">"Flex/Bison"</span><span class="punc-t">,</span> <span class="str-t">"Azure AI"</span><span class="punc-t">],</span>`,
      `    <span class="prop-t">"desktop"</span><span class="punc-t">:</span> <span class="punc-t">[</span><span class="str-t">"Python/PyQt5"</span><span class="punc-t">,</span> <span class="str-t">".NET C#"</span><span class="punc-t">]</span>`,
      `  <span class="punc-t">}</span>`,
      `<span class="punc-t">}</span>`,
    ],
  },
};

export const FILE_KEYS: FileKey[] = [
  "about", "skills", "experience", "projects",
  "demos", "contact", "config",
];