import { DEMO_PROJECTS, DemoProject } from "@/src/lib/demo-projects";
export type FileKey =
  | "about"
  | "skills"
  | "experience"
  | "projects"
  | "demos"
  | "contact"
  | "config";

export interface FileData {
  name: string;
  lang: string;
  icon: "ts" | "json" | "mdx" | "pdf";
  lines: string[];
  demos?: DemoProject[];
}

export const FILES: Record<FileKey, FileData> = {
    // ── about.ts ──────────────────────────────────────────────────────────────
  about: {
    name: "about.ts",
    lang: "TypeScript",
    icon: "ts",
    lines: [
      `<span class="kw2">import</span> <span class="kw">type</span> <span class="punc-t">{</span> <span class="type-t">Developer</span> <span class="punc-t">}</span> <span class="kw2">from</span> <span class="str-t">"./types"</span><span class="punc-t">;</span>`,
      ``,
      `<span class="kw">const</span> <span class="fn-t">about</span><span class="punc-t">:</span> <span class="type-t">Developer</span> <span class="op-t">=</span> <span class="punc-t">{</span>`,
      ``,
      `  <span class="prop-t">name</span><span class="punc-t">:</span>     <span class="str-t">"LAOUITI Malika"</span><span class="punc-t">,</span>`,
      `  <span class="prop-t">role</span><span class="punc-t">:</span>     <span class="str-t">"Fullstack Developer &amp; Systems Engineer"</span><span class="punc-t">,</span>`,
      ``,
      `  <span class="prop-t">education</span><span class="punc-t">: {</span>`,
      `    <span class="prop-t">current</span><span class="punc-t">:</span>  <span class="str-t">"1st Year Software Engineering — ISSAT Sousse (2025–present)"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">degree</span><span class="punc-t">:</span>   <span class="str-t">"BSc Software Engineering — ISIMM Monastir (2025)"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">fyp</span><span class="punc-t">:</span>      <span class="str-t">"Excellent — SourceLang compiler project"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">cert</span><span class="punc-t">:</span>     <span class="str-t">"CCNA 1 — Networking fundamentals"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">bac</span><span class="punc-t">:</span>      <span class="str-t">"Bac Technologique — Ibn Khaldoun Jemmel"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">grade</span><span class="punc-t">:</span>    <span class="num-t">15.73</span> <span class="op-t">/</span> <span class="num-t">20</span><span class="punc-t">,</span>`,
      `  <span class="punc-t">},</span>`,
      ``,
      `  <span class="prop-t">status</span><span class="punc-t">: {</span>`,
      `    <span class="prop-t">seeking</span><span class="punc-t">:</span>   <span class="str-t">"internship — software / web / systems development"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">location</span><span class="punc-t">:</span>  <span class="str-t">"Monastir 5020 🇹🇳"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">available</span><span class="punc-t">:</span> <span class="bool-t">true</span><span class="punc-t">,</span>`,
      `  <span class="punc-t">},</span>`,
      ``,
      `<span class="punc-t">};</span>`,
      ``,
      `<span class="kw2">export default</span> <span class="fn-t">about</span><span class="punc-t">;</span>`,
    ],
  },
 
  // ── skills.ts ─────────────────────────────────────────────────────────────
  skills: {
    name: "skills.ts",
    lang: "TypeScript",
    icon: "ts",
    lines: [
      `<span class="kw2">export</span> <span class="kw">const</span> <span class="fn-t">skills</span> <span class="op-t">=</span> <span class="punc-t">{</span>`,
      ``,
      `  <span class="cmt-t">// ── Programming Languages ──────────────────────</span>`,
      `  <span class="prop-t">languages</span><span class="punc-t">:</span> <span class="punc-t">[</span>`,
      `    <span class="str-t">"Python"</span><span class="punc-t">,</span> <span class="str-t">"C"</span><span class="punc-t">,</span> <span class="str-t">"C++"</span><span class="punc-t">,</span> <span class="str-t">"Java"</span><span class="punc-t">,</span> <span class="str-t">"C#"</span><span class="punc-t">,</span>`,
      `    <span class="str-t">"SQL"</span><span class="punc-t">,</span> <span class="str-t">"PL/SQL"</span><span class="punc-t">,</span> <span class="str-t">"JavaScript"</span><span class="punc-t">,</span> <span class="str-t">"TypeScript"</span><span class="punc-t">,</span>`,
      `  <span class="punc-t">],</span>`,
      ``,
      `  <span class="cmt-t">// ── Web ────────────────────────────────────────</span>`,
      `  <span class="prop-t">web</span><span class="punc-t">:</span> <span class="punc-t">[</span>`,
      `    <span class="str-t">"HTML"</span><span class="punc-t">,</span> <span class="str-t">"CSS"</span><span class="punc-t">,</span> <span class="str-t">"Tailwind"</span><span class="punc-t">,</span>`,
      `    <span class="str-t">"React"</span><span class="punc-t">,</span> <span class="str-t">"Next.js 15"</span><span class="punc-t">,</span> <span class="str-t">"Node.js"</span><span class="punc-t">,</span> <span class="str-t">"Express.js"</span><span class="punc-t">,</span> <span class="str-t">"Vercel"</span><span class="punc-t">,</span>`,
      `  <span class="punc-t">],</span>`,
      ``,
      `  <span class="cmt-t">// ── Databases ──────────────────────────────────</span>`,
      `  <span class="prop-t">databases</span><span class="punc-t">:</span> <span class="punc-t">[</span><span class="str-t">"MySQL"</span><span class="punc-t">,</span> <span class="str-t">"PostgreSQL"</span><span class="punc-t">,</span> <span class="str-t">"MongoDB"</span><span class="punc-t">],</span>`,
      ``,
      `  <span class="cmt-t">// ── Systems & Desktop ──────────────────────────</span>`,
      `  <span class="prop-t">systems</span><span class="punc-t">:</span>  <span class="punc-t">[</span><span class="str-t">"C"</span><span class="punc-t">,</span> <span class="str-t">"C++"</span><span class="punc-t">,</span> <span class="str-t">"Linux"</span><span class="punc-t">],</span>`,
      `  <span class="prop-t">desktop</span><span class="punc-t">:</span>  <span class="punc-t">[</span><span class="str-t">".NET / C#"</span><span class="punc-t">,</span> <span class="str-t">"PyQt5"</span><span class="punc-t">],</span>`,
      ``,
      `  <span class="cmt-t">// ── Compilers & AI — FYP focus ─────────────────</span>`,
      `  <span class="prop-t">compilers</span><span class="punc-t">:</span> <span class="punc-t">[</span><span class="str-t">"Flex"</span><span class="punc-t">,</span> <span class="str-t">"Bison"</span><span class="punc-t">,</span> <span class="str-t">"AST generation"</span><span class="punc-t">],</span>`,
      `  <span class="prop-t">ai</span><span class="punc-t">:</span>        <span class="punc-t">[</span><span class="str-t">"Azure AI Vision"</span><span class="punc-t">],</span>`,
      ``,
      `  <span class="cmt-t">// ── Networking & Tools ─────────────────────────</span>`,
      `  <span class="prop-t">network</span><span class="punc-t">:</span>   <span class="punc-t">[</span><span class="str-t">"CCNA 1 Certified"</span><span class="punc-t">],</span>`,
      `  <span class="prop-t">tools</span><span class="punc-t">:</span>     <span class="punc-t">[</span><span class="str-t">"Git"</span><span class="punc-t">,</span> <span class="str-t">"GitHub"</span><span class="punc-t">],</span>`,
      ``,
      `<span class="punc-t">}</span> <span class="kw">as const</span><span class="punc-t">;</span>`,
    ],
  },
 
  // ── experience.ts ─────────────────────────────────────────────────────────
  experience: {
    name: "experience.ts",
    lang: "TypeScript",
    icon: "ts",
    lines: [
      `<span class="kw2">import</span> <span class="kw">type</span> <span class="punc-t">{</span> <span class="type-t">Experience</span> <span class="punc-t">}</span> <span class="kw2">from</span> <span class="str-t">"./types"</span><span class="punc-t">;</span>`,
      ``,
      `<span class="kw2">export</span> <span class="kw">const</span> <span class="fn-t">experience</span><span class="punc-t">:</span> <span class="type-t">Experience</span><span class="punc-t">[]</span> <span class="op-t">=</span> <span class="punc-t">[</span>`,
      ``,
      `  <span class="cmt-t">// ── Internship — YottaByte ─────────────────────</span>`,
      `  <span class="punc-t">{</span>`,
      `    <span class="prop-t">type</span><span class="punc-t">:</span>    <span class="str-t">"Internship"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">company</span><span class="punc-t">:</span> <span class="str-t">"YottaByte — Monastir, Tunisia"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">period</span><span class="punc-t">:</span>  <span class="str-t">"July 2025 – August 2025"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">mission</span><span class="punc-t">:</span> <span class="str-t">"Web app integrating 6–10 external APIs"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">stack</span><span class="punc-t">:</span>   <span class="punc-t">[</span><span class="str-t">"Next.js 15"</span><span class="punc-t">,</span> <span class="str-t">"Express.js"</span><span class="punc-t">,</span> <span class="str-t">"TypeScript"</span><span class="punc-t">],</span>`,
      `    <span class="prop-t">tasks</span><span class="punc-t">:</span>   <span class="punc-t">[</span>`,
      `      <span class="str-t">"Customizable dashboard UI"</span><span class="punc-t">,</span>`,
      `      <span class="str-t">"Express backend — public API integration &amp; data viz"</span><span class="punc-t">,</span>`,
      `    <span class="punc-t">],</span>`,
      `  <span class="punc-t">},</span>`,
      ``,
      `  <span class="cmt-t">// ── Final Year Project — ISIMM Monastir ────────</span>`,
      `  <span class="punc-t">{</span>`,
      `    <span class="prop-t">type</span><span class="punc-t">:</span>    <span class="str-t">"FYP"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">company</span><span class="punc-t">:</span> <span class="str-t">"ISIMM Monastir — Tunisia"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">period</span><span class="punc-t">:</span>  <span class="str-t">"January 2025 – June 2025"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">mission</span><span class="punc-t">:</span> <span class="str-t">"Fullstack programming language dedicated to the web"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">stack</span><span class="punc-t">:</span>   <span class="punc-t">[</span><span class="str-t">"C"</span><span class="punc-t">,</span> <span class="str-t">"Flex"</span><span class="punc-t">,</span> <span class="str-t">"Bison"</span><span class="punc-t">,</span> <span class="str-t">"AST generation"</span><span class="punc-t">],</span>`,
      `    <span class="prop-t">tasks</span><span class="punc-t">:</span>   <span class="punc-t">[</span><span class="str-t">"Flex/Bison transpiler → AST → web code"</span><span class="punc-t">],</span>`,
      `    <span class="prop-t">grade</span><span class="punc-t">:</span>   <span class="str-t">"Excellent"</span><span class="punc-t">,</span>`,
      `  <span class="punc-t">},</span>`,
      ``,
      `  <span class="cmt-t">// ── Internship — WebProSoft ────────────────────</span>`,
      `  <span class="punc-t">{</span>`,
      `    <span class="prop-t">type</span><span class="punc-t">:</span>    <span class="str-t">"Internship"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">company</span><span class="punc-t">:</span> <span class="str-t">"WebProSoft — Monastir, Tunisia"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">period</span><span class="punc-t">:</span>  <span class="str-t">"June 2024 – July 2024"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">mission</span><span class="punc-t">:</span> <span class="str-t">"Desktop/Web image recognition platform"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">stack</span><span class="punc-t">:</span>   <span class="punc-t">[</span><span class="str-t">".NET C#"</span><span class="punc-t">,</span> <span class="str-t">"HTML/JS"</span><span class="punc-t">,</span> <span class="str-t">"Azure AI Models"</span><span class="punc-t">],</span>`,
      `    <span class="prop-t">tasks</span><span class="punc-t">:</span>   <span class="punc-t">[</span><span class="str-t">"Intuitive UI + Azure AI Vision integration"</span><span class="punc-t">],</span>`,
      `    <span class="prop-t">grade</span><span class="punc-t">:</span>   <span class="str-t">"Excellent"</span><span class="punc-t">,</span>`,
      `  <span class="punc-t">},</span>`,
      ``,
      `  <span class="cmt-t">// ── Freelance ──────────────────────────────────</span>`,
      `  <span class="punc-t">{</span>`,
      `    <span class="prop-t">type</span><span class="punc-t">:</span>    <span class="str-t">"Freelance"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">company</span><span class="punc-t">:</span> <span class="str-t">"Independent client — Remote, Tunisia"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">period</span><span class="punc-t">:</span>  <span class="str-t">"January 2024 – March 2024"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">mission</span><span class="punc-t">:</span> <span class="str-t">"Desktop application — business management"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">stack</span><span class="punc-t">:</span>   <span class="punc-t">[</span><span class="str-t">"Python"</span><span class="punc-t">,</span> <span class="str-t">"PyQt5"</span><span class="punc-t">,</span> <span class="str-t">"MySQL"</span><span class="punc-t">],</span>`,
      `  <span class="punc-t">},</span>`,
      ``,
      `  <span class="cmt-t">// ── Academic Project — ISIMM ───────────────────</span>`,
      `  <span class="punc-t">{</span>`,
      `    <span class="prop-t">type</span><span class="punc-t">:</span>    <span class="str-t">"Academic"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">company</span><span class="punc-t">:</span> <span class="str-t">"ISIMM Monastir — Tunisia"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">period</span><span class="punc-t">:</span>  <span class="str-t">"January 2023 – March 2023"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">mission</span><span class="punc-t">:</span> <span class="str-t">"Patient records &amp; disease management application"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">stack</span><span class="punc-t">:</span>   <span class="punc-t">[</span><span class="str-t">"Python"</span><span class="punc-t">,</span> <span class="str-t">"PyQt5"</span><span class="punc-t">,</span> <span class="str-t">"MySQL"</span><span class="punc-t">,</span> <span class="str-t">"SQL"</span><span class="punc-t">],</span>`,
      `  <span class="punc-t">},</span>`,
      ``,
      `<span class="punc-t">];</span>`,
    ],
  },
 
  // ── projects.ts ───────────────────────────────────────────────────────────
  projects: {
    name: "projects.ts",
    lang: "TypeScript",
    icon: "ts",
    lines: [
      `<span class="kw2">import</span> <span class="kw">type</span> <span class="punc-t">{</span> <span class="type-t">Project</span> <span class="punc-t">}</span> <span class="kw2">from</span> <span class="str-t">"./types"</span><span class="punc-t">;</span>`,
      ``,
      `<span class="kw2">export</span> <span class="kw">const</span> <span class="fn-t">projects</span><span class="punc-t">:</span> <span class="type-t">Project</span><span class="punc-t">[]</span> <span class="op-t">=</span> <span class="punc-t">[</span>`,
      ``,
      `  <span class="cmt-t">// ── Open-Dash — YottaByte Internship ───────────</span>`,
      `  <span class="punc-t">{</span>`,
      `    <span class="prop-t">title</span><span class="punc-t">:</span>   <span class="str-t">"🌐 Open-Dash (Live Data Platform)"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">context</span><span class="punc-t">:</span> <span class="str-t">"Internship — YottaByte, Monastir"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">period</span><span class="punc-t">:</span>  <span class="str-t">"July – August 2025"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">stack</span><span class="punc-t">:</span>   <span class="punc-t">[</span><span class="str-t">"Next.js 15"</span><span class="punc-t">,</span> <span class="str-t">"Leaflet"</span><span class="punc-t">,</span> <span class="str-t">"Chart.js"</span><span class="punc-t">,</span> <span class="str-t">"Express"</span><span class="punc-t">],</span>`,
      `    <span class="prop-t">demo</span><span class="punc-t">:</span>    <span class="str-t">"https://opendash.vercel.app"</span><span class="punc-t">,</span>`,
      `  <span class="punc-t">},</span>`,
      ``,
      `  <span class="cmt-t">// ── SourceLang — Final Year Project ISIMM ──────</span>`,
      `  <span class="punc-t">{</span>`,
      `    <span class="prop-t">title</span><span class="punc-t">:</span>   <span class="str-t">"⚙️  SourceLang (my own programming language)"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">context</span><span class="punc-t">:</span> <span class="str-t">"FYP — ISIMM Monastir"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">period</span><span class="punc-t">:</span>  <span class="str-t">"January – June 2025"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">stack</span><span class="punc-t">:</span>   <span class="punc-t">[</span><span class="str-t">"C"</span><span class="punc-t">,</span> <span class="str-t">"Flex"</span><span class="punc-t">,</span> <span class="str-t">"Bison"</span><span class="punc-t">,</span> <span class="str-t">"AST → web code"</span><span class="punc-t">],</span>`,
      `    <span class="prop-t">grade</span><span class="punc-t">:</span>   <span class="str-t">"Excellent"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">docs</span><span class="punc-t">:</span>    <span class="str-t">"https://sourcelang.vercel.app"</span><span class="punc-t">,</span>`,
      `  <span class="punc-t">},</span>`,
      ``,
      `  <span class="cmt-t">// ── Analytics Dashboard — Personal Project ──────</span>`,
      `  <span class="punc-t">{</span>`,
      `    <span class="prop-t">title</span><span class="punc-t">:</span>    <span class="str-t">"📊 Internship Analytics Dashboard"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">context</span><span class="punc-t">:</span>  <span class="str-t">"Personal project"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">stack</span><span class="punc-t">:</span>    <span class="punc-t">[</span><span class="str-t">"Next.js"</span><span class="punc-t">,</span> <span class="str-t">"TypeScript"</span><span class="punc-t">,</span> <span class="str-t">"MongoDB"</span><span class="punc-t">],</span>`,
      `    <span class="prop-t">features</span><span class="punc-t">:</span> <span class="punc-t">[</span>`,
      `      <span class="str-t">"Upload Excel"</span><span class="punc-t">,</span> <span class="str-t">"Parse"</span><span class="punc-t">,</span> <span class="str-t">"Filter"</span><span class="punc-t">,</span>`,
      `      <span class="str-t">"Export JSON"</span><span class="punc-t">,</span> <span class="str-t">"Visualize"</span><span class="punc-t">,</span> <span class="str-t">"Analyze Data"</span><span class="punc-t">,</span>`,
      `    <span class="punc-t">],</span>`,
      `    <span class="prop-t">demo</span><span class="punc-t">:</span>     <span class="str-t">"https://pfe-internship-isimm.netlify.app/dashboard"</span><span class="punc-t">,</span>`,
      `  <span class="punc-t">},</span>`,
      ``,
      `  <span class="cmt-t">// ── Image Recognition — WebProSoft Internship ───</span>`,
      `  <span class="punc-t">{</span>`,
      `    <span class="prop-t">title</span><span class="punc-t">:</span>   <span class="str-t">"🤖 Image Recognition Platform"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">context</span><span class="punc-t">:</span> <span class="str-t">"Internship — WebProSoft, Monastir"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">period</span><span class="punc-t">:</span>  <span class="str-t">"June – July 2024"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">stack</span><span class="punc-t">:</span>   <span class="punc-t">[</span><span class="str-t">".NET C#"</span><span class="punc-t">,</span> <span class="str-t">"HTML/JS"</span><span class="punc-t">,</span> <span class="str-t">"Azure AI Models"</span><span class="punc-t">],</span>`,
      `    <span class="prop-t">grade</span><span class="punc-t">:</span>   <span class="str-t">"Excellent"</span><span class="punc-t">,</span>`,
      `  <span class="punc-t">},</span>`,
      ``,
      `<span class="punc-t">];</span>`,
      ``,
      `<span class="cmt-t">// 🔗 github.com/MalikaLaouiti</span>`,
    ],
  },
 
  // ── demos.tsx ─────────────────────────────────────────────────────────────
  demos: {
    name: "demos.tsx",
    lang: "TypeScript",
    icon: "mdx",
    demos: DEMO_PROJECTS,
    lines: [
      `<span class="kw2">import</span> <span class="type-t">React</span> <span class="kw2">from</span> <span class="str-t">"react"</span><span class="punc-t">;</span>`,
      `<span class="kw2">import</span> <span class="punc-t">{</span> <span class="type-t">DemoCard</span> <span class="punc-t">}</span> <span class="kw2">from</span> <span class="str-t">"@/components/ui"</span><span class="punc-t">;</span>`,
      ``,
      `<span class="cmt-t">/**</span>`,
      `<span class="cmt-t"> * LIVE DEMOS</span>`,
      `<span class="cmt-t"> * Deployed projects — click to preview or open</span>`,
      `<span class="cmt-t"> */</span>`,
      ``,
      `<span class="kw">const</span> <span class="fn-t">DemosPage</span><span class="punc-t">:</span> <span class="type-t">React.FC</span> <span class="op-t">=</span> <span class="punc-t">() =&gt; {</span>`,
      `  <span class="kw2">return</span> <span class="punc-t">(</span>`,
      `    <span class="punc-t">&lt;</span><span class="type-t">main</span><span class="punc-t">&gt;</span>`,
      ``,
      `      <span class="cmt-t">{/* ─── LIVE — Open-Dash ─── */}</span>`,
      `      <span class="punc-t">&lt;</span><span class="type-t">DemoCard</span>`,
      `        <span class="prop-t">title</span><span class="op-t">=</span><span class="str-t">"🌐 Open-Dash"</span>`,
      `        <span class="prop-t">url</span><span class="op-t">=</span><span class="str-t">"https://opendash.vercel.app"</span>`,
      `        <span class="prop-t">badge</span><span class="op-t">=</span><span class="str-t">"LIVE"</span>`,
      `      <span class="punc-t">/&gt;</span>`,
      ``,
      `      <span class="cmt-t">{/* ─── LIVE — SourceLang ─── */}</span>`,
      `      <span class="punc-t">&lt;</span><span class="type-t">DemoCard</span>`,
      `        <span class="prop-t">title</span><span class="op-t">=</span><span class="str-t">"⚙️  SourceLang"</span>`,
      `        <span class="prop-t">url</span><span class="op-t">=</span><span class="str-t">"https://sourcelang.vercel.app"</span>`,
      `        <span class="prop-t">badge</span><span class="op-t">=</span><span class="str-t">"LIVE"</span>`,
      `      <span class="punc-t">/&gt;</span>`,
      ``,
      `      <span class="cmt-t">{/* ─── LIVE — Analytics Dashboard ─── */}</span>`,
      `      <span class="punc-t">&lt;</span><span class="type-t">DemoCard</span>`,
      `        <span class="prop-t">title</span><span class="op-t">=</span><span class="str-t">"📊 Internship Analytics Dashboard"</span>`,
      `        <span class="prop-t">url</span><span class="op-t">=</span><span class="str-t">"https://pfe-internship-isimm.netlify.app/dashboard"</span>`,
      `        <span class="prop-t">badge</span><span class="op-t">=</span><span class="str-t">"LIVE"</span>`,
      `      <span class="punc-t">/&gt;</span>`,
      ``,
      `      <span class="cmt-t">{/* ─── GitHub — Image Recognition ─── */}</span>`,
      `      <span class="punc-t">&lt;</span><span class="type-t">DemoCard</span>`,
      `        <span class="prop-t">title</span><span class="op-t">=</span><span class="str-t">"🤖 Image Recognition (Azure AI)"</span>`,
      `        <span class="prop-t">url</span><span class="op-t">=</span><span class="str-t">"https://github.com/MalikaLaouiti"</span>`,
      `        <span class="prop-t">badge</span><span class="op-t">=</span><span class="str-t">"GitHub"</span>`,
      `      <span class="punc-t">/&gt;</span>`,
      ``,
      `    <span class="punc-t">&lt;/</span><span class="type-t">main</span><span class="punc-t">&gt;</span>`,
      `  <span class="punc-t">);</span>`,
      `<span class="punc-t">};</span>`,
      ``,
      `<span class="kw2">export default</span> <span class="fn-t">DemosPage</span><span class="punc-t">;</span>`,
    ],
  },
 
  // ── contact.ts ────────────────────────────────────────────────────────────
  contact: {
    name: "contact.ts",
    lang: "TypeScript",
    icon: "ts",
    lines: [
      `<span class="kw2">import</span> <span class="kw">type</span> <span class="punc-t">{</span> <span class="type-t">ContactInfo</span> <span class="punc-t">}</span> <span class="kw2">from</span> <span class="str-t">"./types"</span><span class="punc-t">;</span>`,
      ``,
      `<span class="kw2">export</span> <span class="kw">const</span> <span class="fn-t">contact</span><span class="punc-t">:</span> <span class="type-t">ContactInfo</span> <span class="op-t">=</span> <span class="punc-t">{</span>`,
      ``,
      `  <span class="prop-t">email</span><span class="punc-t">:</span>    <span class="str-t">"laouiti.malika@yahoo.com"</span><span class="punc-t">,</span>`,
      `  <span class="prop-t">phone</span><span class="punc-t">:</span>    <span class="str-t">"+216 25 731 613"</span><span class="punc-t">,</span>`,
      `  <span class="prop-t">github</span><span class="punc-t">:</span>   <span class="str-t">"github.com/MalikaLaouiti"</span><span class="punc-t">,</span>`,
      `  <span class="prop-t">linkedin</span><span class="punc-t">:</span> <span class="str-t">"linkedin.com/in/malika-laouiti"</span><span class="punc-t">,</span>`,
      `  <span class="prop-t">location</span><span class="punc-t">:</span> <span class="str-t">"Cité El Feth, Jemmel, Monastir 5020 🇹🇳"</span><span class="punc-t">,</span>`,
      ``,
      `  <span class="cmt-t">// available immediately — software / web / systems internship</span>`,
      `  <span class="prop-t">available</span><span class="punc-t">:</span> <span class="bool-t">true</span><span class="punc-t">,</span>`,
      ``,
      `<span class="punc-t">};</span>`,
    ],
  },
 
  // ── package.json ──────────────────────────────────────────────────────────
  config: {
    name: "package.json",
    lang: "JSON",
    icon: "json",
    lines: [
      `<span class="punc-t">{</span>`,
      `  <span class="prop-t">"name"</span><span class="punc-t">:</span>        <span class="str-t">"malika-laouiti-portfolio"</span><span class="punc-t">,</span>`,
      `  <span class="prop-t">"version"</span><span class="punc-t">:</span>     <span class="str-t">"1.0.0"</span><span class="punc-t">,</span>`,
      `  <span class="prop-t">"author"</span><span class="punc-t">:</span>      <span class="str-t">"LAOUITI Malika"</span><span class="punc-t">,</span>`,
      `  <span class="prop-t">"description"</span><span class="punc-t">:</span> <span class="str-t">"Fullstack Developer &amp; Systems Engineer"</span><span class="punc-t">,</span>`,
      `  <span class="prop-t">"available"</span><span class="punc-t">:</span>   <span class="bool-t">true</span><span class="punc-t">,</span>`,
      `  <span class="prop-t">"education"</span><span class="punc-t">: {</span>`,
      `    <span class="prop-t">"current"</span><span class="punc-t">:</span>  <span class="str-t">"Software Engineering — ISSAT Sousse (2025–present)"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">"degree"</span><span class="punc-t">:</span>   <span class="str-t">"BSc Software Engineering — ISIMM Monastir (2025)"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">"cert"</span><span class="punc-t">:</span>     <span class="str-t">"CCNA 1"</span>`,
      `  <span class="punc-t">},</span>`,
      `  <span class="prop-t">"scripts"</span><span class="punc-t">: {</span>`,
      `    <span class="prop-t">"demo"</span><span class="punc-t">:</span>    <span class="str-t">"open https://opendash.vercel.app"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">"github"</span><span class="punc-t">:</span>  <span class="str-t">"open github.com/MalikaLaouiti"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">"contact"</span><span class="punc-t">:</span> <span class="str-t">"mailto:Laouiti.malika@yahoo.com"</span>`,
      `  <span class="punc-t">},</span>`,
      `  <span class="prop-t">"stack"</span><span class="punc-t">: {</span>`,
      `    <span class="prop-t">"web"</span><span class="punc-t">:</span>     <span class="punc-t">[</span><span class="str-t">"React"</span><span class="punc-t">,</span> <span class="str-t">"Next.js 15"</span><span class="punc-t">,</span> <span class="str-t">"TypeScript"</span><span class="punc-t">,</span> <span class="str-t">"Tailwind"</span><span class="punc-t">],</span>`,
      `    <span class="prop-t">"backend"</span><span class="punc-t">:</span> <span class="punc-t">[</span><span class="str-t">"Node.js"</span><span class="punc-t">,</span> <span class="str-t">"Express.js"</span><span class="punc-t">,</span> <span class="str-t">"MySQL"</span><span class="punc-t">,</span> <span class="str-t">"PostgreSQL"</span><span class="punc-t">,</span> <span class="str-t">"MongoDB"</span><span class="punc-t">],</span>`,
      `    <span class="prop-t">"systems"</span><span class="punc-t">:</span> <span class="punc-t">[</span><span class="str-t">"C"</span><span class="punc-t">,</span> <span class="str-t">"C++"</span><span class="punc-t">,</span> <span class="str-t">"Linux"</span><span class="punc-t">,</span> <span class="str-t">"Flex/Bison"</span><span class="punc-t">,</span> <span class="str-t">"Azure AI"</span><span class="punc-t">],</span>`,
      `    <span class="prop-t">"desktop"</span><span class="punc-t">:</span> <span class="punc-t">[</span><span class="str-t">"Python/PyQt5"</span><span class="punc-t">,</span> <span class="str-t">".NET C#"</span><span class="punc-t">]</span>`,
      `  <span class="punc-t">}</span>`,
      `<span class="punc-t">}</span>`,
    ],
  },
};

export const FILE_KEYS: FileKey[] = [
  "about",
  "skills",
  "experience",
  "projects",
  "demos",
  "contact",
  "config",
];
