import { DEMO_PROJECTS, DemoProject } from "@/src/lib/demo-projects";

export type FileKey =
  | "about"
  | "skills"
  | "experience"
  | "projects"
  | "demos"
  | "documents"  
  | "contact"
  | "config";

export interface FileData {
  name: string;
  lang: string;
  icon: "ts" | "json" | "mdx" | "pdf";
  lines: string[];
  demos?: DemoProject[];
}

export const FILES: Record<FileKey, FileData> = {
  about: {
    name: "about.ts",
    lang: "TypeScript",
    icon: "ts",
    lines: [
      `<span class="kw2">import</span> <span class="kw">type</span> <span class="punc-t">{</span> <span class="type-t">Developer</span> <span class="punc-t">}</span> <span class="kw2">from</span> <span class="str-t">"./types"</span><span class="punc-t">;</span>`,
      ``,
      `<span class="kw">const</span> <span class="fn-t">about</span><span class="punc-t">:</span> <span class="type-t">Developer</span> <span class="op-t">=</span> <span class="punc-t">{</span>`,
      ``,
      `  <span class="prop-t">name</span><span class="punc-t">:</span>     <span class="str-t">"LAOUITI Malika"</span><span class="punc-t">,</span>`,
      `  <span class="prop-t">role</span><span class="punc-t">:</span>     <span class="str-t">"Developer &amp; Systems Engineer"</span><span class="punc-t">,</span>`,
      ``,
      `  <span class="prop-t">education</span><span class="punc-t">: {</span>`,
      `    <span class="prop-t">current</span><span class="punc-t">:</span>  <span class="str-t">"Software Engineering Student — ISSAT Sousse (2025–present)"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">degree</span><span class="punc-t">:</span>   <span class="str-t">"BSc Computer Science, specializing in Software Engineering — ISIMM Monastir (2025)"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">fyp</span><span class="punc-t">:</span>      <span class="str-t">"Excellent — SourceLang compiler project"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">cert</span><span class="punc-t">:</span>     <span class="str-t">"CCNA 1 — Networking fundamentals"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">bac</span><span class="punc-t">:</span>      <span class="str-t">"Bac Technologique — Ibn Khaldoun Jemmel"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">grade</span><span class="punc-t">:</span>    <span class="num-t">15.73</span> <span class="op-t">/</span> <span class="num-t">20</span><span class="punc-t">,</span>`,
      `  <span class="punc-t">},</span>`,
      ``,
      `  <span class="prop-t">status</span><span class="punc-t">: {</span>`,
      `    <span class="prop-t">seeking</span><span class="punc-t">:</span>   <span class="str-t">"internship — software / web / systems development"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">location</span><span class="punc-t">:</span>  <span class="str-t">"Monastir 5020 🇹🇳"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">available</span><span class="punc-t">:</span> <span class="bool-t">true</span><span class="punc-t">,</span>`,
      `  <span class="punc-t">},</span>`,
      ``,
      `<span class="punc-t">};</span>`,
      ``,
      `<span class="kw2">export default</span> <span class="fn-t">about</span><span class="punc-t">;</span>`,
    ],
  },
  skills: {
    name: "skills.ts",
    lang: "TypeScript",
    icon: "ts",
    lines: [
      `<span class="kw2">export</span> <span class="kw">const</span> <span class="fn-t">skills</span> <span class="op-t">=</span> <span class="punc-t">{</span>`,
      ``,
      `  <span class="cmt-t">// ── Programming Languages ──────────────────────</span>`,
      `  <span class="prop-t">languages</span><span class="punc-t">:</span> <span class="punc-t">[</span>`,
      `    <span class="str-t">"Python"</span><span class="punc-t">,</span> <span class="str-t">"C"</span><span class="punc-t">,</span> <span class="str-t">"C++"</span><span class="punc-t">,</span> <span class="str-t">"Java"</span><span class="punc-t">,</span> <span class="str-t">"C#"</span><span class="punc-t">,</span>`,
      `    <span class="str-t">"SQL"</span><span class="punc-t">,</span> <span class="str-t">"PL/SQL"</span><span class="punc-t">,</span> <span class="str-t">"JavaScript"</span><span class="punc-t">,</span> <span class="str-t">"TypeScript"</span><span class="punc-t">,</span>`,
      `  <span class="punc-t">],</span>`,
      ``,
      `  <span class="cmt-t">// ── Web ────────────────────────────────────────</span>`,
      `  <span class="prop-t">web</span><span class="punc-t">:</span> <span class="punc-t">[</span>`,
      `    <span class="str-t">"HTML"</span><span class="punc-t">,</span> <span class="str-t">"CSS"</span><span class="punc-t">,</span> <span class="str-t">"Tailwind"</span><span class="punc-t">,</span>`,
      `    <span class="str-t">"React"</span><span class="punc-t">,</span> <span class="str-t">"Next.js 15"</span><span class="punc-t">,</span> <span class="str-t">"Node.js"</span><span class="punc-t">,</span> <span class="str-t">"Express.js"</span><span class="punc-t">,</span> <span class="str-t">"Vercel"</span><span class="punc-t">,</span>`,
      `  <span class="punc-t">],</span>`,
      ``,
      `  <span class="cmt-t">// ── Databases ──────────────────────────────────</span>`,
      `  <span class="prop-t">databases</span><span class="punc-t">:</span> <span class="punc-t">[</span><span class="str-t">"MySQL"</span><span class="punc-t">,</span> <span class="str-t">"PostgreSQL"</span><span class="punc-t">,</span> <span class="str-t">"MongoDB"</span><span class="punc-t">],</span>`,
      ``,
      `  <span class="cmt-t">// ── Systems & Desktop ──────────────────────────</span>`,
      `  <span class="prop-t">systems</span><span class="punc-t">:</span>  <span class="punc-t">[</span><span class="str-t">"C"</span><span class="punc-t">,</span> <span class="str-t">"C++"</span><span class="punc-t">,</span> <span class="str-t">"Linux"</span><span class="punc-t">],</span>`,
      `  <span class="prop-t">desktop</span><span class="punc-t">:</span>  <span class="punc-t">[</span><span class="str-t">".NET / C#"</span><span class="punc-t">,</span> <span class="str-t">"PyQt5"</span><span class="punc-t">],</span>`,
      ``,
      `  <span class="cmt-t">// ── Compilers & AI — FYP focus ─────────────────</span>`,
      `  <span class="prop-t">compilers</span><span class="punc-t">:</span> <span class="punc-t">[</span><span class="str-t">"Flex"</span><span class="punc-t">,</span> <span class="str-t">"Bison"</span><span class="punc-t">,</span> <span class="str-t">"AST generation"</span><span class="punc-t">],</span>`,
      `  <span class="prop-t">ai</span><span class="punc-t">:</span>        <span class="punc-t">[</span><span class="str-t">"Azure AI Vision"</span><span class="punc-t">],</span>`,
      ``,
      `  <span class="cmt-t">// ── Networking & Tools ─────────────────────────</span>`,
      `  <span class="prop-t">network</span><span class="punc-t">:</span>   <span class="punc-t">[</span><span class="str-t">"CCNA 1 Certified"</span><span class="punc-t">],</span>`,
      `  <span class="prop-t">tools</span><span class="punc-t">:</span>     <span class="punc-t">[</span><span class="str-t">"Git"</span><span class="punc-t">,</span> <span class="str-t">"GitHub"</span><span class="punc-t">],</span>`,
      ``,
      `<span class="punc-t">}</span> <span class="kw">as const</span><span class="punc-t">;</span>`,
    ],
  },

  experience: {
    name: "experience.ts",
    lang: "TypeScript",
    icon: "ts",
    lines: [
      `<span class="kw2">import</span> <span class="kw">type</span> <span class="punc-t">{</span> <span class="type-t">Experience</span> <span class="punc-t">}</span> <span class="kw2">from</span> <span class="str-t">"./types"</span><span class="punc-t">;</span>`,
      ``,
      `<span class="kw2">export</span> <span class="kw">const</span> <span class="fn-t">experience</span><span class="punc-t">:</span> <span class="type-t">Experience</span><span class="punc-t">[]</span> <span class="op-t">=</span> <span class="punc-t">[</span>`,
      ``,
      `  <span class="cmt-t">// ── Stage — YottaByte ──────────────────────────</span>`,
      `  <span class="punc-t">{</span>`,
      `    <span class="prop-t">type</span><span class="punc-t">:</span>     <span class="str-t">"Stage"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">company</span><span class="punc-t">:</span>  <span class="str-t">"YottaByte"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">location</span><span class="punc-t">:</span> <span class="str-t">"Monastir, Tunisie"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">period</span><span class="punc-t">:</span>   <span class="str-t">"Juillet 2025 – Août 2025"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">title</span><span class="punc-t">:</span>    <span class="str-t">"App web multi-API externe (Open-Dash)"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">stack</span><span class="punc-t">:</span>    <span class="punc-t">[</span><span class="str-t">"Next.js 15"</span><span class="punc-t">,</span> <span class="str-t">"Express.js"</span><span class="punc-t">,</span> <span class="str-t">"TypeScript"</span><span class="punc-t">],</span>`,
      `  <span class="punc-t">},</span>`,
      ``,
      `  <span class="cmt-t">// ── PFE — ISIMM ────────────────────────────────</span>`,
      `  <span class="punc-t">{</span>`,
      `    <span class="prop-t">type</span><span class="punc-t">:</span>     <span class="str-t">"PFE"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">company</span><span class="punc-t">:</span>  <span class="str-t">"ISIMM Monastir"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">location</span><span class="punc-t">:</span> <span class="str-t">"Monastir, Tunisie"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">period</span><span class="punc-t">:</span>   <span class="str-t">"Janvier – Juin 2025"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">title</span><span class="punc-t">:</span>    <span class="str-t">"SourceLang — langage FullStack dédié web"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">stack</span><span class="punc-t">:</span>    <span class="punc-t">[</span><span class="str-t">"C"</span><span class="punc-t">,</span> <span class="str-t">"Flex"</span><span class="punc-t">,</span> <span class="str-t">"Bison"</span><span class="punc-t">,</span> <span class="str-t">"AST"</span><span class="punc-t">],</span>`,
      `    <span class="prop-t">mention</span><span class="punc-t">:</span>  <span class="str-t">"Excellent"</span><span class="punc-t">,</span>`,
      `  <span class="punc-t">},</span>`,
      ``,
      `  <span class="cmt-t">// ── Stage — WebProSoft ─────────────────────────</span>`,
      `  <span class="punc-t">{</span>`,
      `    <span class="prop-t">type</span><span class="punc-t">:</span>     <span class="str-t">"Stage"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">company</span><span class="punc-t">:</span>  <span class="str-t">"WebProSoft"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">location</span><span class="punc-t">:</span> <span class="str-t">"Monastir, Tunisie"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">period</span><span class="punc-t">:</span>   <span class="str-t">"Juin – Juillet 2024"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">title</span><span class="punc-t">:</span>    <span class="str-t">"Plateforme Desktop/Web reconnaissance d'images"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">stack</span><span class="punc-t">:</span>    <span class="punc-t">[</span><span class="str-t">".NET C#"</span><span class="punc-t">,</span> <span class="str-t">"HTML/JS"</span><span class="punc-t">,</span> <span class="str-t">"Azure AI"</span><span class="punc-t">],</span>`,
      `  <span class="punc-t">},</span>`,
      ``,
      `  <span class="cmt-t">// ── Freelance ──────────────────────────────────</span>`,
      `  <span class="punc-t">{</span>`,
      `    <span class="prop-t">type</span><span class="punc-t">:</span>     <span class="str-t">"Freelance"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">company</span><span class="punc-t">:</span>  <span class="str-t">"Client indépendant"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">location</span><span class="punc-t">:</span> <span class="str-t">"Remote — Tunisie"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">period</span><span class="punc-t">:</span>   <span class="str-t">"Janvier – Mars 2024"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">title</span><span class="punc-t">:</span>    <span class="str-t">"App desktop — gestion d'entreprise"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">stack</span><span class="punc-t">:</span>    <span class="punc-t">[</span><span class="str-t">"Python"</span><span class="punc-t">,</span> <span class="str-t">"PyQt5"</span><span class="punc-t">,</span> <span class="str-t">"MySQL"</span><span class="punc-t">],</span>`,
      `  <span class="punc-t">},</span>`,
      ``,
      `<span class="punc-t">];</span>`,
    ],
  },

  // ── projects.ts ───────────────────────────────────────────────────────────
  projects: {
    name: "projects.ts",
    lang: "TypeScript",
    icon: "ts",
    lines: [
      `<span class="kw2">import</span> <span class="kw">type</span> <span class="punc-t">{</span> <span class="type-t">Project</span> <span class="punc-t">}</span> <span class="kw2">from</span> <span class="str-t">"./types"</span><span class="punc-t">;</span>`,
      ``,
      `<span class="kw2">export</span> <span class="kw">const</span> <span class="fn-t">projects</span><span class="punc-t">:</span> <span class="type-t">Project</span><span class="punc-t">[]</span> <span class="op-t">=</span> <span class="punc-t">[</span>`,
      ``,
      `  <span class="punc-t">{</span>`,
      `    <span class="prop-t">title</span><span class="punc-t">:</span>   <span class="str-t">"🌐 Open-Dash — Live Data Platform"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">context</span><span class="punc-t">:</span> <span class="str-t">"Stage — YottaByte, Monastir"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">stack</span><span class="punc-t">:</span>   <span class="punc-t">[</span><span class="str-t">"Next.js 15"</span><span class="punc-t">,</span> <span class="str-t">"Leaflet"</span><span class="punc-t">,</span> <span class="str-t">"Chart.js"</span><span class="punc-t">,</span> <span class="str-t">"Express"</span><span class="punc-t">],</span>`,
      `    <span class="prop-t">demo</span><span class="punc-t">:</span>    <span class="link-t">"https://opendash.vercel.app"</span><span class="punc-t">,</span>`,
      `  <span class="punc-t">},</span>`,
      `  <span class="punc-t">{</span>`,
      `    <span class="prop-t">title</span><span class="punc-t">:</span>   <span class="str-t">"⚙️  SourceLang — custom compiler"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">context</span><span class="punc-t">:</span> <span class="str-t">"PFE — ISIMM Monastir (mention Excellent)"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">stack</span><span class="punc-t">:</span>   <span class="punc-t">[</span><span class="str-t">"C"</span><span class="punc-t">,</span> <span class="str-t">"Flex"</span><span class="punc-t">,</span> <span class="str-t">"Bison"</span><span class="punc-t">,</span> <span class="str-t">"AST"</span><span class="punc-t">],</span>`,
      `    <span class="prop-t">demo</span><span class="punc-t">:</span>    <span class="link-t">"https://sourcelang.vercel.app"</span><span class="punc-t">,</span>`,
      `  <span class="punc-t">},</span>`,
      `  <span class="punc-t">{</span>`,
      `    <span class="prop-t">title</span><span class="punc-t">:</span>   <span class="str-t">"📊 Internship Analytics Dashboard"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">stack</span><span class="punc-t">:</span>   <span class="punc-t">[</span><span class="str-t">"Next.js"</span><span class="punc-t">,</span> <span class="str-t">"TypeScript"</span><span class="punc-t">,</span> <span class="str-t">"MongoDB"</span><span class="punc-t">],</span>`,
      `    <span class="prop-t">demo</span><span class="punc-t">:</span>    <span class="link-t">"https://pfe-internship-isimm.netlify.app/dashboard"</span><span class="punc-t">,</span>`,
      `  <span class="punc-t">},</span>`,
      `  <span class="punc-t">{</span>`,
      `    <span class="prop-t">title</span><span class="punc-t">:</span>   <span class="str-t">"🤖 Image Recognition Platform"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">context</span><span class="punc-t">:</span> <span class="str-t">"Stage — WebProSoft, Monastir"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">stack</span><span class="punc-t">:</span>   <span class="punc-t">[</span><span class="str-t">".NET C#"</span><span class="punc-t">,</span> <span class="str-t">"HTML/JS"</span><span class="punc-t">,</span> <span class="str-t">"Azure AI"</span><span class="punc-t">],</span>`,
      `    <span class="prop-t">repo</span><span class="punc-t">:</span>    <span class="link-t">"github.com/MalikaLaouiti"</span><span class="punc-t">,</span>`,
      `  <span class="punc-t">},</span>`,
      ``,
      `<span class="punc-t">];</span>`,
    ],
  },

  // ── demos.tsx ─────────────────────────────────────────────────────────────
  demos: {
    name: "demos.tsx",
    lang: "TSX",
    icon: "mdx",
    demos: DEMO_PROJECTS,
    lines: [
      `<span class="kw2">import</span> <span class="type-t">DemoCard</span> <span class="kw2">from</span> <span class="str-t">"./components/DemoCard"</span><span class="punc-t">;</span>`,
      ``,
      `<span class="kw2">export</span> <span class="kw">const</span> <span class="fn-t">DemosPage</span> <span class="op-t">=</span> <span class="punc-t">() =&gt; (</span>`,
      `  <span class="punc-t">&lt;</span><span class="type-t">main</span><span class="punc-t">&gt;</span>`,
      `    <span class="cmt-t">{/* ─── LIVE — Open-Dash ─── */}</span>`,
      `    <span class="punc-t">&lt;</span><span class="type-t">DemoCard</span> <span class="prop-t">title</span><span class="op-t">=</span><span class="str-t">"🌐 Open-Dash"</span>`,
      `      <span class="prop-t">url</span><span class="op-t">=</span><span class="str-t">"https://opendash.vercel.app"</span> <span class="prop-t">badge</span><span class="op-t">=</span><span class="str-t">"LIVE"</span> <span class="punc-t">/&gt;</span>`,
      `    <span class="cmt-t">{/* ─── LIVE — SourceLang ─── */}</span>`,
      `    <span class="punc-t">&lt;</span><span class="type-t">DemoCard</span> <span class="prop-t">title</span><span class="op-t">=</span><span class="str-t">"⚙️  SourceLang"</span>`,
      `      <span class="prop-t">url</span><span class="op-t">=</span><span class="str-t">"https://sourcelang.vercel.app"</span> <span class="prop-t">badge</span><span class="op-t">=</span><span class="str-t">"LIVE"</span> <span class="punc-t">/&gt;</span>`,
      `    <span class="cmt-t">{/* ─── LIVE — Analytics ─── */}</span>`,
      `    <span class="punc-t">&lt;</span><span class="type-t">DemoCard</span> <span class="prop-t">title</span><span class="op-t">=</span><span class="str-t">"📊 Internship Dashboard"</span>`,
      `      <span class="prop-t">url</span><span class="op-t">=</span><span class="str-t">"https://pfe-internship-isimm.netlify.app/dashboard"</span> <span class="prop-t">badge</span><span class="op-t">=</span><span class="str-t">"LIVE"</span> <span class="punc-t">/&gt;</span>`,
      `    <span class="cmt-t">{/* ─── GitHub — Image Recognition ─── */}</span>`,
      `    <span class="punc-t">&lt;</span><span class="type-t">DemoCard</span> <span class="prop-t">title</span><span class="op-t">=</span><span class="str-t">"🤖 Image Recognition"</span>`,
      `      <span class="prop-t">url</span><span class="op-t">=</span><span class="str-t">"https://github.com/MalikaLaouiti"</span> <span class="prop-t">badge</span><span class="op-t">=</span><span class="str-t">"GitHub"</span> <span class="punc-t">/&gt;</span>`,
      `  <span class="punc-t">&lt;/</span><span class="type-t">main</span><span class="punc-t">&gt;</span>`,
      `<span class="punc-t">);</span>`,
      ``,
      `<span class="kw2">export default</span> <span class="fn-t">DemosPage</span><span class="punc-t">;</span>`,
    ],
  },

  documents: {
    name: "documents.ts",
    lang: "TypeScript",
    icon: "pdf",   
    lines: [
      `<span class="kw2">import</span> <span class="kw">type</span> <span class="punc-t">{</span> <span class="type-t">Document</span><span class="punc-t">,</span> <span class="type-t">DocStatus</span> <span class="punc-t">}</span> <span class="kw2">from</span> <span class="str-t">"./types"</span><span class="punc-t">;</span>`,
      ``,
      `<span class="cmt-t">// ── Types (pour référence) ────────────────────────────────</span>`,
      `<span class="cmt-t">// type DocStatus = "available" | "on-request";</span>`,
      `<span class="cmt-t">// interface Document {</span>`,
      `<span class="cmt-t">//   category: string;  title: string;</span>`,
      `<span class="cmt-t">//   file: string;       status: DocStatus;</span>`,
      `<span class="cmt-t">// }</span>`,
      ``,
      `<span class="kw2">export</span> <span class="kw">const</span> <span class="fn-t">documents</span><span class="punc-t">:</span> <span class="type-t">Document</span><span class="punc-t">[]</span> <span class="op-t">=</span> <span class="punc-t">[</span>`,
      ``,
      `  <span class="cmt-t">// ── CV ─────────────────────────────────────────────────</span>`,
      `  <span class="punc-t">{</span>`,
      `    <span class="prop-t">category</span><span class="punc-t">:</span> <span class="str-t">"CV"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">title</span><span class="punc-t">:</span>    <span class="str-t">"Curriculum Vitæ — LAOUITI Malika"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">year</span><span class="punc-t">:</span>     <span class="num-t">2025</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">file</span><span class="punc-t">:</span>     <span class="link-t">"/documents/CV-MalikaLaouiti.pdf"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">status</span><span class="punc-t">:</span>   <span class="str-t">"available"</span><span class="punc-t">,</span>`,
      `  <span class="punc-t">},</span>`,
      ``,
      `  <span class="cmt-t">// ── Attestations de Stage ──────────────────────────────</span>`,
      `  <span class="punc-t">{</span>`,
      `    <span class="prop-t">category</span><span class="punc-t">:</span> <span class="str-t">"Attestation de Stage"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">title</span><span class="punc-t">:</span>    <span class="str-t">"YottaByte — Juillet–Août 2025"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">company</span><span class="punc-t">:</span>  <span class="str-t">"YottaByte, Monastir"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">file</span><span class="punc-t">:</span>     <span class="link-t">"/documents/attestation-yottabyte-2025.pdf"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">status</span><span class="punc-t">:</span>   <span class="str-t">"available"</span><span class="punc-t">,</span>`,
      `  <span class="punc-t">},</span>`,
      `  <span class="punc-t">{</span>`,
      `    <span class="prop-t">category</span><span class="punc-t">:</span> <span class="str-t">"Attestation de Stage"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">title</span><span class="punc-t">:</span>    <span class="str-t">"WebProSoft — Juin–Juillet 2024"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">company</span><span class="punc-t">:</span>  <span class="str-t">"WebProSoft, Monastir"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">file</span><span class="punc-t">:</span>     <span class="link-t">"/documents/attestation-webprosoft-2024.pdf"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">status</span><span class="punc-t">:</span>   <span class="str-t">"available"</span><span class="punc-t">,</span>`,
      `  <span class="punc-t">},</span>`,
      ``,
      `  <span class="cmt-t">// ── Certificat ─────────────────────────────────────────</span>`,
      `  <span class="punc-t">{</span>`,
      `    <span class="prop-t">category</span><span class="punc-t">:</span> <span class="str-t">"Certificat"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">title</span><span class="punc-t">:</span>    <span class="str-t">"CCNA 1 — Introduction to Networks"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">issuer</span><span class="punc-t">:</span>   <span class="str-t">"Cisco Networking Academy"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">file</span><span class="punc-t">:</span>     <span class="link-t">"/documents/certificat-ccna1.pdf"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">status</span><span class="punc-t">:</span>   <span class="str-t">"available"</span><span class="punc-t">,</span>`,
      `  <span class="punc-t">},</span>`,
      ``,
      `  <span class="cmt-t">// ── Diplômes ───────────────────────────────────────────</span>`,
      `  <span class="punc-t">{</span>`,
      `    <span class="prop-t">category</span><span class="punc-t">:</span> <span class="str-t">"Diplôme"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">title</span><span class="punc-t">:</span>    <span class="str-t">"Licence GL & SI — ISIMM Monastir"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">mention</span><span class="punc-t">:</span>  <span class="str-t">"Excellent (FYP: SourceLang)"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">year</span><span class="punc-t">:</span>     <span class="num-t">2025</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">file</span><span class="punc-t">:</span>     <span class="link-t">"/documents/diplome-licence-isimm-2025.pdf"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">status</span><span class="punc-t">:</span>   <span class="str-t">"available"</span><span class="punc-t">,</span>`,
      `  <span class="punc-t">},</span>`,
      `  <span class="punc-t">{</span>`,
      `    <span class="prop-t">category</span><span class="punc-t">:</span> <span class="str-t">"Baccalauréat"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">title</span><span class="punc-t">:</span>    <span class="str-t">"Bac Technologique — Ibn Khaldoun Jemmel"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">grade</span><span class="punc-t">:</span>    <span class="num-t">15.73</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">year</span><span class="punc-t">:</span>     <span class="num-t">2022</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">file</span><span class="punc-t">:</span>     <span class="link-t">"/documents/baccalaureat-2022.pdf"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">status</span><span class="punc-t">:</span>   <span class="str-t">"available"</span><span class="punc-t">,</span>`,
      `  <span class="punc-t">},</span>`,
      ``,
      `  <span class="cmt-t">// ── Relevé de notes ────────────────────────────────────</span>`,
      `  <span class="punc-t">{</span>`,
      `    <span class="prop-t">category</span><span class="punc-t">:</span> <span class="str-t">"Relevé de notes"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">title</span><span class="punc-t">:</span>    <span class="str-t">"Relevé — Licence ISIMM (2022–2025)"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">file</span><span class="punc-t">:</span>     <span class="link-t">"/documents/releve-notes-licence.pdf"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">status</span><span class="punc-t">:</span>   <span class="str-t">"on-request"</span><span class="punc-t">,</span>  <span class="cmt-t">// disponible sur demande</span>`,
      `  <span class="punc-t">},</span>`,
      ``,
      `<span class="punc-t">];</span>`,
      ``,
      `<span class="cmt-t">// ℹ️  Pour télécharger : cliquer sur le bouton de chaque carte</span>`,
      `<span class="cmt-t">// ℹ️  Placer les PDF dans /public/documents/ avec les noms ci-dessus</span>`,
      `<span class="cmt-t">// ℹ️  Contact : laouiti.malika@yahoo.com</span>`,
    ],
  },

  // ── contact.ts ────────────────────────────────────────────────────────────
  contact: {
    name: "contact.ts",
    lang: "TypeScript",
    icon: "ts",
    lines: [
      `<span class="kw2">import</span> <span class="kw">type</span> <span class="punc-t">{</span> <span class="type-t">ContactInfo</span> <span class="punc-t">}</span> <span class="kw2">from</span> <span class="str-t">"./types"</span><span class="punc-t">;</span>`,
      ``,
      `<span class="kw2">export</span> <span class="kw">const</span> <span class="fn-t">contact</span><span class="punc-t">:</span> <span class="type-t">ContactInfo</span> <span class="op-t">=</span> <span class="punc-t">{</span>`,
      ``,
      `  <span class="prop-t">email</span><span class="punc-t">:</span>    <span class="str-t">"laouiti.malika@yahoo.com"</span><span class="punc-t">,</span>`,
      `  <span class="prop-t">phone</span><span class="punc-t">:</span>    <span class="str-t">"+216 25 731 613"</span><span class="punc-t">,</span>`,
      `  <span class="prop-t">github</span><span class="punc-t">:</span>   <span class="str-t">"github.com/MalikaLaouiti"</span><span class="punc-t">,</span>`,
      `  <span class="prop-t">linkedin</span><span class="punc-t">:</span> <span class="str-t">"linkedin.com/in/malika-laouiti"</span><span class="punc-t">,</span>`,
      `  <span class="prop-t">location</span><span class="punc-t">:</span> <span class="str-t">"Cité El Feth, Jemmel, Monastir 5020 🇹🇳"</span><span class="punc-t">,</span>`,
      ``,
      `  <span class="cmt-t">// available immediately — software / web / systems internship</span>`,
      `  <span class="prop-t">available</span><span class="punc-t">:</span> <span class="bool-t">true</span><span class="punc-t">,</span>`,
      ``,
      `<span class="punc-t">};</span>`,
    ],
  },

  // ── package.json ──────────────────────────────────────────────────────────
  config: {
    name: "package.json",
    lang: "JSON",
    icon: "json",
    lines: [
      `<span class="punc-t">{</span>`,
      `  <span class="prop-t">"name"</span><span class="punc-t">:</span>        <span class="str-t">"malika-laouiti-portfolio"</span><span class="punc-t">,</span>`,
      `  <span class="prop-t">"version"</span><span class="punc-t">:</span>     <span class="str-t">"1.0.0"</span><span class="punc-t">,</span>`,
      `  <span class="prop-t">"author"</span><span class="punc-t">:</span>      <span class="str-t">"LAOUITI Malika"</span><span class="punc-t">,</span>`,
      `  <span class="prop-t">"description"</span><span class="punc-t">:</span> <span class="str-t">"Fullstack Developer &amp; Systems Engineer"</span><span class="punc-t">,</span>`,
      `  <span class="prop-t">"available"</span><span class="punc-t">:</span>   <span class="bool-t">true</span><span class="punc-t">,</span>`,
      `  <span class="prop-t">"education"</span><span class="punc-t">: {</span>`,
      `    <span class="prop-t">"current"</span><span class="punc-t">:</span>  <span class="str-t">"Software Engineering — ISSAT Sousse (2025–present)"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">"degree"</span><span class="punc-t">:</span>   <span class="str-t">"BSc Software Engineering — ISIMM Monastir (2025)"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">"cert"</span><span class="punc-t">:</span>     <span class="str-t">"CCNA 1"</span>`,
      `  <span class="punc-t">},</span>`,
      `  <span class="prop-t">"scripts"</span><span class="punc-t">: {</span>`,
      `    <span class="prop-t">"demo"</span><span class="punc-t">:</span>    <span class="str-t">"open https://opendash.vercel.app"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">"github"</span><span class="punc-t">:</span>  <span class="str-t">"open github.com/MalikaLaouiti"</span><span class="punc-t">,</span>`,
      `    <span class="prop-t">"contact"</span><span class="punc-t">:</span> <span class="str-t">"mailto:Laouiti.malika@yahoo.com"</span>`,
      `  <span class="punc-t">},</span>`,
      `  <span class="prop-t">"stack"</span><span class="punc-t">: {</span>`,
      `    <span class="prop-t">"web"</span><span class="punc-t">:</span>     <span class="punc-t">[</span><span class="str-t">"React"</span><span class="punc-t">,</span> <span class="str-t">"Next.js 15"</span><span class="punc-t">,</span> <span class="str-t">"TypeScript"</span><span class="punc-t">,</span> <span class="str-t">"Tailwind"</span><span class="punc-t">],</span>`,
      `    <span class="prop-t">"backend"</span><span class="punc-t">:</span> <span class="punc-t">[</span><span class="str-t">"Node.js"</span><span class="punc-t">,</span> <span class="str-t">"Express.js"</span><span class="punc-t">,</span> <span class="str-t">"MySQL"</span><span class="punc-t">,</span> <span class="str-t">"PostgreSQL"</span><span class="punc-t">,</span> <span class="str-t">"MongoDB"</span><span class="punc-t">],</span>`,
      `    <span class="prop-t">"systems"</span><span class="punc-t">:</span> <span class="punc-t">[</span><span class="str-t">"C"</span><span class="punc-t">,</span> <span class="str-t">"C++"</span><span class="punc-t">,</span> <span class="str-t">"Linux"</span><span class="punc-t">,</span> <span class="str-t">"Flex/Bison"</span><span class="punc-t">,</span> <span class="str-t">"Azure AI"</span><span class="punc-t">],</span>`,
      `    <span class="prop-t">"desktop"</span><span class="punc-t">:</span> <span class="punc-t">[</span><span class="str-t">"Python/PyQt5"</span><span class="punc-t">,</span> <span class="str-t">".NET C#"</span><span class="punc-t">]</span>`,
      `  <span class="punc-t">}</span>`,
      `<span class="punc-t">}</span>`,
    ],
  },
};

export const FILE_KEYS: FileKey[] = [
  "about", "skills", "experience", "projects",
  "demos", "documents", "contact", "config",
];